### ISSUE TITLE
[RPi3] Unable to compile from the source 

### ISSUE THREAD

**Issue by LodanZark** [libretro/libretro-fceumm#108]
Unable to compile from the source on RPi3

Probably the error its related to the board unrom512.o

Log started at: Sun 30 Apr 00:19:06 UTC 2017
/home/pi/RetroPie-Setup/tmp/build/lr-fceumm /home/pi

= = = = = = = = = = = = = = = = = = = = =
Getting sources for 'lr-fceumm' : NES emu - FCEUmm port for libretro
= = = = = = = = = = = = = = = = = = = = =

git clone --recursive --depth 1 "https://github.com/libretro/libretro-fceumm.git" "/home/pi/RetroPie-Setup/tmp/build/lr-fceumm"
Cloning into '/home/pi/RetroPie-Setup/tmp/build/lr-fceumm'...
/home/pi
/home/pi/RetroPie-Setup/tmp/build/lr-fceumm /home/pi

= = = = = = = = = = = = = = = = = = = = =
Building 'lr-fceumm' : NES emu - FCEUmm port for libretro
= = = = = = = = = = = = = = = = = = = = =

rm -f src/boards/57.o src/boards/222.o src/boards/99.o src/boards/vrc2and4.o src/boards/411120-c.o src/boards/158B.o src/boards/bb.o src/boards/15.o src/boards/193.o src/boards/emu2413.o src/boards/79.o src/boards/77.o src/boards/69.o src/boards/kof97.o src/boards/transformer.o src/boards/f-15.o src/boards/234.o src/boards/mmc2and4.o src/boards/subor.o src/boards/830118C.o src/boards/8237.o src/boards/91.o src/boards/unrom512.o src/boards/mihunche.o src/boards/vrc1.o src/boards/71.o src/boards/bandai.o src/boards/51.o src/boards/novel.o src/boards/41.o src/boards/208.o src/boards/108.o src/boards/vrc7.o src/boards/175.o src/boards/supervision.o src/boards/eh8813a.o src/boards/232.o src/boards/36.o src/boards/h2288.o src/boards/super24.o src/boards/copyfami_hwi.o src/boards/gs-2004.o src/boards/177.o src/boards/datalatch.o src/boards/90.o src/boards/185.o src/boards/mmc5.o src/boards/coolboy.o src/boards/96.o src/boards/hp898f.o src/boards/onebus.o src/boards/106.o src/boards/ax5705.o src/boards/190.o src/boards/80.o src/boards/yoko.o src/boards/edu2000.o src/boards/50.o src/boards/40.o src/boards/mmc3.o src/boards/206.o src/boards/104.o src/boards/34.o src/boards/mmc1.o src/boards/tengen.o src/boards/pec-586.o src/boards/121.o src/boards/addrlatch.o src/boards/67.o src/boards/225.o src/boards/88.o src/boards/246.o src/boards/vrc7p.o src/boards/09-034a.o src/boards/bmc64in1nr.o src/boards/8in1.o src/boards/112.o src/boards/bmc13in1jy110.o src/boards/n625092.o src/boards/252.o src/boards/164.o src/boards/BMW8544.o src/boards/KS7037.o src/boards/n106.o src/boards/lh32.o src/boards/et-100.o src/boards/186.o src/boards/68.o src/boards/bmc42in1r.o src/boards/gs-2013.o src/boards/18.o src/boards/ghostbusters63in1.o src/boards/3d-block.o src/boards/189.o src/boards/a9746.o src/boards/copyfami_emu.o src/boards/malee.o src/boards/244.o src/boards/KS7013.o src/boards/120.o src/boards/KS7031.o src/boards/bonza.o src/boards/235.o src/boards/KS7017.o src/boards/sachen.o src/boards/t-262.o src/boards/bmc70in1.o src/boards/253.o src/boards/199.o src/boards/ffe.o src/boards/le05.o src/boards/cityfighter.o src/boards/117.o src/boards/82.o src/boards/vrc3.o src/boards/72.o src/boards/SA-9602B.o src/boards/62.o src/boards/t-227-1.o src/boards/KS7057.o src/boards/fk23c.o src/boards/bs-5.o src/boards/168.o src/boards/42.o src/boards/et-4320.o src/boards/ac-08.o src/boards/__serial.o src/boards/32.o src/boards/183.o src/boards/famicombox.o src/boards/156.o src/boards/187.o src/boards/151.o src/boards/230.o src/boards/KS7030.o src/boards/65.o src/boards/dance2000.o src/boards/KS7012.o src/boards/KS7032.o src/boards/170.o src/boards/sc-127.o src/boards/8157.o src/boards/ks7016.o src/boards/103.o src/boards/tf-1201.o src/boards/__dummy_mapper.o src/boards/603-5052.o src/boards/lh53.o src/boards/46.o src/boards/01-222.o src/boards/vrc5.o src/boards/116.o src/boards/12in1.o src/boards/43.o src/boards/karaoke.o src/boards/sheroes.o src/boards/dream.o src/boards/vrc6.o src/boards/33.o src/boards/178.o src/boards/228.o src/boards/sl1632.o src/input/fkb.o src/input/quiz.o src/input/suborkb.o src/input/pads.o src/input/hypershot.o src/input/bbox.o src/input/cursor.o src/input/bworld.o src/input/arkanoid.o src/input/ftrainer.o src/input/oekakids.o src/input/mouse.o src/input/shadow.o src/input/mahjong.o src/input/zapper.o src/input/powerpad.o src/input/toprider.o src/input/pec586kb.o src/drivers/libretro/griffin.o src/ines.o src/unif.o src/x6502.o
rm -f fceumm_libretro.so
cc -c -o src/boards/57.o src/boards/57.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/222.o src/boards/222.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/99.o src/boards/99.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/vrc2and4.o src/boards/vrc2and4.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/411120-c.o src/boards/411120-c.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/158B.o src/boards/158B.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/bb.o src/boards/bb.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/15.o src/boards/15.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/193.o src/boards/193.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/emu2413.o src/boards/emu2413.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/79.o src/boards/79.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/77.o src/boards/77.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/69.o src/boards/69.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/kof97.o src/boards/kof97.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/transformer.o src/boards/transformer.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/f-15.o src/boards/f-15.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/234.o src/boards/234.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/mmc2and4.o src/boards/mmc2and4.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/subor.o src/boards/subor.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/830118C.o src/boards/830118C.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/8237.o src/boards/8237.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/91.o src/boards/91.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/unrom512.o src/boards/unrom512.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
cc -c -o src/boards/mihunche.o src/boards/mihunche.c -O2 -march=armv8-a+crc -mtune=cortex-a53 -mfpu=neon-fp-armv8 -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -pipe -DGIT_VERSION=\"" a298950"\" -O3 -DNDEBUG -DWANT_GRIFFIN  -fPIC -Wno-write-strings -D__LIBRETRO__ -DSOUND_QUALITY=0 -DPATH_MAX=1024 -DINLINE=inline -DFCEU_VERSION_NUMERIC=9813 -DFRONTEND_SUPPORTS_RGB565  -DPSS_STYLE=1  -Isrc/drivers/libretro -Isrc -Isrc/input -Isrc/boards -Isrc/mappers
src/boards/unrom512.c: In function ‘UNROM512LSync’:
src/boards/unrom512.c:196:4: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
    for(uint32 i=0;i<(ROM_size*4);i++)
    ^
src/boards/unrom512.c:196:4: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
Makefile.libretro:352: recipe for target 'src/boards/unrom512.o' failed
make: *** [src/boards/unrom512.o] Error 1
make: *** Waiting for unfinished jobs....
/home/pi
Could not successfully build lr-fceumm - NES emu - FCEUmm port for libretro (/home/pi/RetroPie-Setup/tmp/build/lr-fceumm/fceumm_libretro.so not found).

Log ended at: Sun 30 Apr 00:19:29 UTC 2017
Total running time: 0 hours, 0 mins, 23 secs

**Comment by retro-wertz** [comment]
please re-fetch new buildfix commit and try.

**Comment by LodanZark** [comment]
it's working now, thank you
