### ISSUE TITLE
Issues on PSP Nightly

### ISSUE THREAD

**Issue by ChrisHighwind** [libretro/libretro-fceumm#11]
I don't know if this affects other devices, but attempting to use the fceumm core on the nightly builds of RetroArch PSP leaves games with a yellow tint regardless of palette choice, and causes the games to run at ~40 FPS 
![pic_0012](https://cloud.githubusercontent.com/assets/10728382/5923126/0088d636-a61f-11e4-8d51-395919be2b18.png)

**Comment by retro-wertz** [comment]
i hope somebody with psp can test this... else since there has been no update probably need to close?

**Comment by hizzlekizzle** [comment]
Yeah, gonna close it. Feel free to reopen if the problem still exists.
