### ISSUE TITLE
RetroArchievement : memory map size?

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-fceumm#119]
more investigation needed..........................

**Comment by leiradel** [comment]
When the core implements the memory map interface, `retro_get_memory_data/size` aren't used for achievements, so we need to map all available RAM. And even if it wasn't so, the memory map should map all the system's memory. My implementation for FCEUmm is incomplete in that sense, since the cartridge ROM is not mapped.

**Comment by retro-wertz** [comment]
my original post got through? hehe. i did replace my post and closed this one since since some normal cheevos did not work. and since RAM is at 0x0-0x400 and WRAM has maximum size of 32768(only 1 mapper is at least 16768 and another 1 more is 32K, while most are 8192) which starts at 0x6000, it was correct to map all 65536 bytes of ram.

i did tested and was able to have all WRAM global but log window would not make sense(since RAM already used CHEEEVOS system RAM info).

my original post was about if there is memory overhead with this and if so if we can lessen it(for low memory devices fceumm supports?) if we somehow we reused resources already available(in this case variable which is already used in FCEU_AddCheatRAM which is RAM and WRAM(from each mappers).

anyways i was just bored and was trying out stuff.

**Comment by leiradel** [comment]
There's no overhead, it's just the sharing of existing memory via pointers to RetroArch. The only overhead is one memory descriptor entry for each mapped memory, a few dozen bytes per entry.
