### ISSUE TITLE
Problems with NES core in PSP nightly builds

### ISSUE THREAD

**Issue by Quickgold74** [libretro/libretro-fceumm#12]
With any nightly build (after beta 2), when I using FCEUmm core my PSP stuck reading the game for 10 seconds the screen go black after this crash, only with the beta 2 for slim works fine for me but FCEUmm won't save states and FDS games isn't work either, I'm using CFW PSP 3000 on 6.60 LME-2.3.

**Comment by retro-wertz** [comment]
i hope somebody with psp can test this... else since there has been no update probably need to close?

**Comment by hizzlekizzle** [comment]
Yep, closing. Feel free to reopen if the problem persists.
