### ISSUE TITLE
Android build broken

### ISSUE THREAD

**Issue by fr500** [libretro/libretro-fceumm#126]
<retrobot> fceumm-armeabi: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/27362
<retrobot> fceumm-armeabi-v7a: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/27364
<retrobot> fceumm-x86: [status: fail] [recipes/android/cores-android-jni] LOG: http://p.0bl.net/27365

**Comment by retro-wertz** [comment]
android should be compiling now....

**Comment by meepingsnesroms** [comment]
There in the buildbot again as of Oct 6 2017.
