### ISSUE TITLE
Dragon Slayer 4 / Wagyan Land issues

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/libretro-fceumm#151]
Dragon Slayer 4 - Drasle Family (Japan) starts with a bugged background, game is not playable.
It works fine with Nestopia.

Relevant parts of the log:
```
[INFO] Loading content file: E:\Emulateurs\RetroArch64\cache\Dragon Slayer 4 - Drasle Family (Japan).nes.
[INFO] CRC32: 0xe1539190 .
[libretro INFO]  PRG ROM:    8 x 16KiB
[libretro INFO]  CHR ROM:    8 x  8KiB
[libretro INFO]  ROM CRC32:  0xa5e6baf9
[libretro INFO]  ROM MD5:  0xcf3db55cdad3d58426c5589cf08da750
[libretro INFO]  Mapper #:  4
[libretro INFO]  Mapper name: MMC3
[libretro INFO]  Mirroring: Horizontal
[libretro INFO]  Battery-backed: No
[libretro INFO]  Trained: No
```
Doing a search,[ I saw it mentioned here with Mirroring:Vertical](http://tuxnes.sourceforge.net/nesmapper.txt).
Is that the issue?

**Comment by Tatsuya79** [comment]
Another game with bad issues is Wagyan Land and it's the same type of cart too:
```
[INFO] CRC32: 0x6eb4d2b8 .
[libretro INFO] Loading E:\Emulateurs\RetroArch64\cache\Wagyan Land (Japan).nes...
[libretro INFO]  PRG ROM:    8 x 16KiB
[libretro INFO]  CHR ROM:    8 x  8KiB
[libretro INFO]  ROM CRC32:  0x2a01f9d1
[libretro INFO]  ROM MD5:  0x60d03e838fc7c90cdf35c68cd265a0fa
[libretro INFO]  Mapper #:  4
[libretro INFO]  Mapper name: MMC3
[libretro INFO]  Mirroring: Horizontal
[libretro INFO]  Battery-backed: No
[libretro INFO]  Trained: No
```
Also referenced with Mirroring:Vertical in that list on previous post.

**Comment by Tatsuya79** [comment]
Lupin Sansei - Pandora no Isan (Japan) seems to have problems too.

> [libretro INFO]  PRG ROM:    8 x 16KiB
> [libretro INFO]  CHR ROM:    8 x  8KiB
> [libretro INFO]  ROM CRC32:  0x9d21fe96
> [libretro INFO]  ROM MD5:  0x58357d9d6fac462b9fc7fd8194bf0e66
> [libretro INFO]  Mapper #:  4
> [libretro INFO]  Mapper name: MMC3
> [libretro INFO]  Mirroring: Horizontal
> [libretro INFO]  Battery-backed: No
> [libretro INFO]  Trained: No

**Comment by retro-wertz** [comment]
these roms all all Mapper 206 - NAMCOT 108. Rev.C roms and are all working if have the correct header info:

```
Dragon Slayer 4 - Drasle Family (Japan).nes...
[libretro INFO]  PRG ROM:    8 x 16KiB
[libretro INFO]  CHR ROM:    8 x  8KiB
[libretro INFO]  ROM CRC32:  0xa5e6baf9
[libretro INFO]  ROM MD5:  0xcf3db55cdad3d58426c5589cf08da750
[libretro INFO]  Mapper #:  206
[libretro INFO]  Mapper name: NAMCOT 108 Rev. C
[libretro INFO]  Mirroring: Vertical
[libretro INFO]  Battery-backed: No
[libretro INFO]  Trained: No


Wagyan Land (Japan).nes...
[libretro INFO]  PRG ROM:    8 x 16KiB
[libretro INFO]  CHR ROM:    8 x  8KiB
[libretro INFO]  ROM CRC32:  0x2a01f9d1
[libretro INFO]  ROM MD5:  0x60d03e838fc7c90cdf35c68cd265a0fa
[libretro INFO]  Mapper #:  206
[libretro INFO]  Mapper name: NAMCOT 108 Rev. C
[libretro INFO]  Mirroring: Vertical
[libretro INFO]  Battery-backed: No
[libretro INFO]  Trained: No
[libretro INFO] 


Lupin Sansei - Pandora no Isan (Japan).nes...
[libretro INFO]  PRG ROM:    8 x 16KiB
[libretro INFO]  CHR ROM:    8 x  8KiB
[libretro INFO]  ROM CRC32:  0x9d21fe96
[libretro INFO]  ROM MD5:  0x58357d9d6fac462b9fc7fd8194bf0e66
[libretro INFO]  Mapper #:  206
[libretro INFO]  Mapper name: NAMCOT 108 Rev. C
[libretro INFO]  Mirroring: Vertical
[libretro INFO]  Battery-backed: No
[libretro INFO]  Trained: No
```

Note: Clrmame does not check headers for NES roms and intentionally skips it when scanning (1st 16bytes), and there are lots of rompacks out there that verifies fine but do not have correct header info. 

Here are other other problematic roms so far:
https://github.com/libretro/libretro-fceumm/issues/106
https://github.com/libretro/libretro-fceumm/issues/99

**Comment by retro-wertz** [comment]
added them to database:

**Comment by Tatsuya79** [comment]
Thanks they're working now. 👍 
I'll know where to change that if I find more.

**Comment by retro-wertz** [comment]
i often added to database when there are mapper specific mods required by the rom, that way when the rom is loaded the necessary mapper and mods will also be loaded.

Still its better to fix the header, especially if you use soft-patching for fceumm, as this will alter the crc when loaded and correct header will not be applied.
