### ISSUE TITLE
no FCEUmm mouse input with Windows sdl2 input driver

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-fceumm#156]
- Operating System: Windows 7 x64
- RA Version: 1.6.7 stable
- ROM tested: Chiller (USA) (Unl)

I have tested this hardware and OS four ways:
1. `dinput` input driver in Nestopia
2. `dinput` input driver in FCEUmm
3. `sdl2` input driver in Nestopia
4. `sdl2` input driver in FCEUmm

Every test worked as expected, except test 4. Some issue is preventing FCEUmm from receiving the mouse input from `sdl2` although the logs do show the mouse being recognized.

Logs: https://pastebin.com/0F9M9fB1

**Comment by retro-wertz** [comment]
sdl2 works fine here with my mouse both absolute and relative modes.

dinput works fine too with both absolute and relative modes.

raw driver though only relative mode works, no inputs in absolute.

**Comment by markwkidd** [comment]
I've just double-checked and I get the same results with `sdl2` -- not even the mouse buttons work in FCEUmm with `sdl2`, while everything works fine with Nestopia.

**Comment by retro-wertz** [comment]
there is not problem on my side. if it worked for nestopia, then it should
work with fceumm in relative mode since its both using
retro_device_lightgun/mouse for that. take note, zapper should be on port 2
for normal nes roms and port1 for vs unisystem games. these are not
autoconfigured like nestopia does.

**Comment by markwkidd** [comment]
Are you running in Linux? I'm Windows which might be a clue.

Please see below the screenshots for how I have set up all of the input settings for my FCEUmm/SDL2 test. Can you see anything that I need to alter?

(Note that I'm just testing regular 'relative' mice with this, not the Wiimote/Dolphinbar.)

![screenshot 2017-09-25 15 12 30](https://user-images.githubusercontent.com/19554678/30826397-821d6d5e-a204-11e7-9521-4a529b96c84f.png)
![screenshot 2017-09-25 15 12 40](https://user-images.githubusercontent.com/19554678/30826398-8235c2dc-a204-11e7-944a-09cd909a223d.png)
![screenshot 2017-09-25 15 13 53](https://user-images.githubusercontent.com/19554678/30826399-82466fb0-a204-11e7-8072-2f72392b5072.png)
![screenshot 2017-09-25 15 14 09](https://user-images.githubusercontent.com/19554678/30826400-824d3cdc-a204-11e7-9df3-f567cc7a1b20.png)

**Comment by retro-wertz** [comment]
im not sure if you already loaded the core with a game running, since its
suppose to show Gamepad for user1/2, not Retropad. and user2 should be
zapper

**Comment by markwkidd** [comment]
Thank you @retro-wertz you helped me figure out my mistake. I will add a section to the FCEUmm core docs describing how to use the zapper. 

@retro-wertz could you make sure this procedure looks correct?

In order to use a mouse to emulate the NES Zapper, follow these steps:

- Load a Famicom or NES ROM in the FCEUmm core
- Access the RetroArch Quick Menu
- In the Input Settings for User 1, specify a device type of Gamepad
- In the Input Settings for User 2, specify a device type of Zapper
- Exit the Quick Menu

**Comment by retro-wertz** [comment]
when playing normal nes roms, yes, User 2/player 2 port should be set to
Zapper.

when using VS Unisystem roms, Zapper should be set to User1/player 1 port.
if this is not done, rom will sound an alarm if zapper is not connected.

this is typically how the NES communicated with the zapper.

**Comment by markwkidd** [comment]
Thanks @retro-wertz 

Here is my new draft for the FCEUmm docs:

------

**Zapper**
FCEUmm is able to emulate the Nintendo Zapper accessory in one of two ways.

**For standard Famicom/NES ROMs:**

- Load a standard Famicom or NES ROM in the FCEUmm core
- Access the RetroArch Quick Menu
- In the Input Settings for User 1, specify a device type of Gamepad
- In the Input Settings for User 2, specify a device type of Zapper
- Exit the Quick Menu

**For VS Unisystem ROMs:**

- Load a VS Unisystem ROM in the FCEUmm core
- Access the RetroArch Quick Menu
- In the Input Settings for User 1, specify a device type of Zapper
- Exit the Quick Menu

**Comment by retro-wertz** [comment]
looks fine. probably put the warning alarm in VS Unisystem if Zapper is not connected in User1/Player1 port. user can just reset the core to silence the alarm and continue playing. VS. Duck Hunt is better than regular duck hunt-you can shoot the dog at the bonus stages :D

**Comment by markwkidd** [comment]
thanks @retro-wertz , I added a note below the VS Unisystem instructions.

"Note: In VS Unisystem mode, if the 'zapper' device is not connected in the Player 1 port the core will display an error message. In that case the user can reset the core to silence the warning and continue playing."

**Comment by retro-wertz** [comment]
actually its not a display-type warning.. but an alarm sound from speaker
as soon as the rom loads. if you have VS.Duck hunt or VS. Hogans Alley it
should be quick to test. the same alarm will be heard if you switch off the
zapper from port 1 while the game is still running.

**Comment by markwkidd** [comment]
Ah ok.

How about this?

"In VS Unisystem mode, if the 'zapper' device is not connected in the Player 1 port the core will generate an alarm sound. In that case the user can reset the core to silence the warning and continue playing."
