### ISSUE TITLE
NES Core on PSP fail to open zipped roms

### ISSUE THREAD

**Issue by Quickgold74** [libretro/libretro-fceumm#17]
When try to open a game in zip or 7z format the NES Core in Retroarch PSP crash the console, only works with extracted roms, in beta 2 I don't have this issue with NES Core.

**Comment by retro-wertz** [comment]
i hope somebody with psp can test this... else since there has been no update probably need to close?

**Comment by meepingsnesroms** [comment]
What about running it in ppsspp, could that work or is retroarch too lowlevel(using kernel mode) for that to work?

**Comment by meepingsnesroms** [comment]
I tried with ppsspp just got a black screen, retroarch wont even load.

**Comment by retro-wertz** [comment]
in any case, this should probably be closed until a similar issue arises or somebody is able to test then...

**Comment by fr500** [comment]
Seems fixed in the latest builds
