### ISSUE TITLE
Hoshi wo Miru Hito (Japan) [En by KingMike v0.80] (~Stargazers) (Incomplete) many glitches

### ISSUE THREAD

**Issue by ofry** [libretro/libretro-fceumm#172]
Original game works fine.

But this translation has too many glitches.

![hoshi wo miru hito japan en by kingmike v0 80 stargazers incomplete -171019-051823](https://user-images.githubusercontent.com/11790863/31751369-a56e6506-b48d-11e7-8ac8-56d616068c2d.png)

```
[libretro INFO] Loading C:\Users\ofry\Downloads\Nintendo - Nintendo Entertainment System\Hoshi o Miru Hito (Japan)\Hoshi wo Miru Hito (Japan) [En by KingMike v0.80] (~Stargazers) (Incomplete).nes...

[libretro INFO]  PRG ROM:   16 x 16KiB
[libretro INFO]  CHR ROM:    0 x  8KiB
[libretro INFO]  ROM CRC32:  0x9ceb6d70
[libretro INFO]  ROM MD5:  0xc619760663fa36c0f958e1b4500eebd4
[libretro INFO]  Mapper #:  2
[libretro INFO]  Mapper name: UNROM
[libretro INFO]  Mirroring: Vertical
[libretro INFO]  Battery-backed: Yes
[libretro INFO]  Trained: No
[libretro INFO]
```

FCEUmm core ce7fe39

Same rom working fine on QuickNES core.

**Comment by ofry** [comment]
This game has 2 translation variants:
1) "conservative" (which I tested - just translation without hacks)
2) "SRAM saving hack" (same as "conservative" + SRAM saving + increased walk speed).

Both you can find on emuparadise, for example. Or you can get patches from romhacking.net

**Comment by retro-wertz** [comment]
the mapper 2 code seems correct. the patch needs no_bus_conflicts which by default is ON for fceux(as the original carts are has bus_conflicts), and save ram enabled (for SRAM version). But even with those temporarily modified for the game, it still has dialog issues wherein test will just keep rolling with an acii "y" - type character. something else is missing...

**Comment by ofry** [comment]
I think this dialog autoscrolling made patch author by intend. This is also on QuickNES too.

**Comment by ofry** [comment]
Tested on Nestopia core too. Same behavior.

**Comment by retro-wertz** [comment]
Ok, looks like i got it...

![hoshi](https://user-images.githubusercontent.com/23315382/31755862-4d3fdb6c-b4d3-11e7-9e1c-335e540734b3.png)


But, the game has to be treated differently than what mapper 2 was coded. which means it should match its CRC for proper identification. im using the Goodnes 3.23 pre-patched translation.

**Comment by ofry** [comment]
OK. Waiting to buildbot compiles this.

**Comment by ofry** [comment]
Big thanks. It fixed :) Congrats!

**Comment by MediaMaquina** [comment]
> But, the game has to be treated differently than what mapper 2 was coded. which means it should match its CRC for proper identification.
![Stargazers (Japan)  T-En by KingMike's Translations v0 80   i   n -0](https://github.com/libretro/libretro-fceumm/assets/8179611/c262ec26-7515-454f-b004-a088d5e8a232)

What to do? I have same issue.
