### ISSUE TITLE
palette bug

### ISSUE THREAD

**Issue by eugene-s-nesdev** [libretro/libretro-fceumm#176]
Hi, i've just found palette bug caused by last commits
step1:
Go to core options and change default palette to RGB 
(its good example because it have very high saturation compared to default palette)
step2:
Try to change Region.

You'll see palette was automatically reset to default palette again, but GUI shows you RGB. 
Need to recheck RGB in core options for correct colors.

In short words: palette resets to "default" every time you change region, but GUI don't show it

**Comment by retro-wertz** [comment]
thanks. PR should fix this.

**Comment by eugene-s-nesdev** [comment]
I forgot to tell: this bug also appears when you load ROM, palette resets to default every time you load new rom
