### ISSUE TITLE
"Kyatto Ninden Teyandee (J) [T+Eng1.01SPC Cartoon_Vice Translations]" (Not working)

### ISSUE THREAD

**Issue by LodanZark** [libretro/libretro-fceumm#178]
Kyatto Ninden Teyandee (J) [T+Eng1.01SPC Cartoon_Vice Translations] (GoodNES 3.23b) doesn't work in the current build, but it works good on FCEUX SVN 3377 (Windows)

**Comment by retro-wertz** [comment]
hi. the game seems to load and run fine here. what crc do you have?

![screenshot_2017-11-06_09-56-03](https://user-images.githubusercontent.com/23315382/32422076-03b2a95c-c2d9-11e7-993b-ca8cf695120f.png)

**Comment by LodanZark** [comment]
Hi, seems I identified the issue, I did renamed "Kyatto Ninden Teyandee (J) [T+Eng1.01SPC Cartoon_Vice Translations]" to "Samurai Pizza Cats  (Japan) [T+Eng1.01]" and by mistake add an extra space between Cats and (Japan), for some reason the game opened as black screen and closed, but after removing the extra space made the game to boot normally, I am not sure if it's an issue related with retropie or retroarch but now the game runs smoothly. I suppose I can close the ticket, thank for your time ;)
