### ISSUE TITLE
(Emscripten) Every sprite looks shifted over.

### ISSUE THREAD

**Issue by hyarsan** [libretro/libretro-fceumm#186]
![mario has seen better days](https://user-images.githubusercontent.com/32988993/34237794-e46db656-e5fe-11e7-8b81-0fd84d502cfd.png)

At least in the game Super Mario Bros, all the sprites are shifted over in Emscripten.
https://buildbot.libretro.com/.web/

**Comment by retro-wertz** [comment]
this should be fixed already as of this posting:

![Uploading Screenshot_2018-01-04_04-12-16.png…]()

**Comment by hyarsan** [comment]
It looks good now, except it is REALLY slow.

**Comment by retro-wertz** [comment]
reopened? why?

**Comment by hyarsan** [comment]
I thought maybe the fix caused it to be really slow?

**Comment by retro-wertz** [comment]
did this even run fast before? even quicknes is slow and has audio stutter
when that core is suppose to have lower resources needed.

**Comment by hyarsan** [comment]
I don't remember it being as bad but then again, I have a ton of tabs open.

**Comment by retro-wertz** [comment]
works fine and playable here in windows.... choppy in linux. so this is not a core issue.

**Comment by hyarsan** [comment]
This whole thing is about emscripten. On all other platforms and cores it works perfectly fine.

**Comment by retro-wertz** [comment]
urgh...................... so you cannot play web player in windows then?

**Comment by hyarsan** [comment]
So it's about Firefox not working properly on Windows? Still about Emscripten. It has been fixed anyway.

**Comment by hizzlekizzle** [comment]
If it's fixed, let's close this.
