### ISSUE TITLE
(Vulkan) The video is messed up!

### ISSUE THREAD

**Issue by hyarsan** [libretro/libretro-fceumm#187]
![eww](https://user-images.githubusercontent.com/32988993/34238187-b8c7dc50-e600-11e7-86bb-20ebf8513917.png)

Yeah... the pause functionality also doesn't work properly so the screenshot functionality and the menu doesn't as well.

**Comment by fr500** [comment]
Sorry pressed by accident.
Interesting, this is the only software accelerated core, dunno what's going wrong here though.

**Comment by twinaphex** [comment]
Cannot reproduce this on my end.

**Comment by hyarsan** [comment]
Nestopia works fine, I am using Windows 10 64-bit.

**Comment by retro-wertz** [comment]
i have issue if using vulkan but it looks more of a pitch issue than what you have(but im on linux as no vulkan driver available for my gpu in windows). try to turn off horizontal overscan in core option if this helps. if not turn off also vertical overscan.

**Comment by hyarsan** [comment]
It doesn't help, just adds black bars to the left and right sides.

**Comment by hizzlekizzle** [comment]
I can reproduce this behavior only when in the menu on my Shield ATV with the vulkan driver. In regular gameplay, it's fine.

**Comment by Tatsuya79** [comment]
Here on win7 x64 nvidia with vulkan, picture is OK in fceumm.
If I hit f1 then it's bugged with the transparent menu on top.

But that PR fixes that https://github.com/libretro/libretro-fceumm/pull/188

**Comment by retro-wertz** [comment]
this should really be closed and 2 others have already tested that the pr has issue on their side...
