### ISSUE TITLE
Glitch with the No-Intro Castlevania (USA) (Rev A) ROM

### ISSUE THREAD

**Issue by Ranthalion75** [libretro/libretro-fceumm#203]
The scoreboard at the top of the screen is stuck to the background and scrolls along with it, scrolling by again later as you progress through the levels. The No-Intro Castlevania (USA) ROM doesn't have this problem.

**Comment by Ranthalion75** [comment]
Awesome!  That fixed it.  Thanks, and sorry for the trouble. 2X-VBlank overclock was the problem. :-)

**Comment by retro-wertz** [comment]
np. please close this issue page.
