### ISSUE TITLE
Translated Roms & MultiTap

### ISSUE THREAD

**Issue by newoski** [libretro/libretro-fceumm#218]
I've got Multitap working fine, with native Famicom games, however, it doesn't work for the English patched translations -- soft and hard patched. I'm fairly certain it's due to the CRC not matching the list FCEUMM uses to "enable" MultiTap. 

If I provide the CRCs, would it be possible to add CRCs for the 8 or so translated games that use MultiTap?

**Comment by retro-wertz** [comment]
its probably better for most cases that 4player input/mode can be forced by a core option or through an entry in one of the controllers options. i already have this function in my local repo but dont have the time to push stuff nowadays.

maybe somebody else notice this and add this feature instead..

**Comment by newoski** [comment]
that would make me equally happy!

**Comment by hizzlekizzle** [comment]
fixed by #229
