### ISSUE TITLE
PSP FCEUmm core reload leads to sytem shutdown

### ISSUE THREAD

**Issue by junaru** [libretro/libretro-fceumm#221]
## Description

On PSP-3003 the FCEUmm core is able to load content only when the core was not previously loaded.
If the core is loaded via "Load core" menu entry or as 'recent' on startup the loading of an uncompressed nes ROM will result in a system shutdown.

### Expected behavior

Content loads 

### Actual behavior

System shuts down when loading content.

### Steps to reproduce the bug

1. Delete /PSP/RETROARCH directory on memory card (nuke all the settings).
2. Download http://buildbot.libretro.com/stable/1.7.3/playstation/psp/RetroArch.7z
3. Extract to /PSP/GAME/RetroArch.
4. Run RetroArch on your PSP.
5. Load fceumm_libretro.PBP core.
6. Try loading any *.nes ROM (uncompressed).
7. When asked choose fceumm_libretro.PBP core again (this might be the step with the bug).

System shuts down.

### Workaround 1

1. Do steps to reproduce the bug.
2. Turn the system back on and launch RetroArch again.
3. Load 81_libretro.PBP core (Sinclair - ZX 81).
4. Try loading any *.nes ROM (uncompressed).
5. When asked choose fceumm_libretro.PBP core.

Content loads fine.

### Workaround 2

1. Do steps to reproduce the bug.
2. Turn the system back on and delete /PSP/RETROARCH/retroarch.cfg
3. Launch RetroArch again. At this time the default core (Sinclair - ZX 81) is automaticaly loaded.
4. Try loading any *.nes ROM (uncompressed)
5. When asked choose fceumm_libretro.PBP core.

Content loads fine.

### Probable cause

IMHO there is something wrong with how RetroArch saves/loads settings and how FCEUmm core tries to read them (maybe a settings rework was done recently?).

Im not sure if this is RetroArch or FCEUmm core issue.

### Version/Commit

- RetroArch: 1.7.3
- FCEUmm: (SVN) 82fd24e (the one shipped with RetroArch 1.7.3.)

### Environment information

- OS: PSP-3003 with custom firmware: Infinity 6.61 LME-2.3

**Comment by retro-wertz** [comment]
RetroArch: 1.7.3 is rather old. try to test with latest nightly and see if this still happens.

**Comment by retro-wertz** [comment]
looks like issue could be similar to states problem in Wii awhile back, some variables are not probably re-initialized after loading another session without switching or closing retroarch entirely and run it again.

can you try if closing retroarch after a session, and running it againg for another game works? also info on what game or games  (hopefully not hacked roms to avoid inconsistencies) are involved? thanks.

**Comment by junaru** [comment]
My apologies for lack of communication on my part.

I have just tested with current RetroArch 1.8.7 and was no longer able to reproduce the issue, whatever it was it looks like its fixed.

Thanks for all your hard work, and sorry again for not clearing this up earlier.
