### ISSUE TITLE
Arkanoid does not move dpad android version

### ISSUE THREAD

**Issue by spielvan** [libretro/libretro-fceumm#230]
Arkanoid does not move the dpad android version, when I try to play the Arkanoid, in the retroarch of android by the core Fceumm, the palette hitting the ball is locked in the corner of the screen without moving, the ball moves normally, with the core nestopia the Arkanoid works normally.

**Comment by spielvan** [comment]
> sent PR for this...

It was perfect now, thank you very much.

**Comment by retro-wertz** [comment]
if i am understanding you right, the dpad problem came back with the last PR? it should not affect input, as those are for palette-related options, though you may want to re-select your Palette options to renew it.

as for the arkanoid problem, try adjusting user inputs to auto or zapper. zappers for NES are on player 2, zappers for VS games are on player 1.

send a log if problems continues.
