### ISSUE TITLE
libretro-fceumm error wii

### ISSUE THREAD

**Issue by rogerioronin** [libretro/libretro-fceumm#238]
The Fceumm Core is locking up on the Nintendo Wii when you use the save state and sometimes when you start the game!

**Comment by retro-wertz** [comment]
We need more information that this...

If you haven't updated fceumm core for quite awhile, an update last March was made older states incompatible with more recent versions.

If you just updated since a few days ago, i made changes for save states as well but those are just mapper specifics (vrc6, 19, 69)

if this is wii-only specific (dont have issues so far on linux) then maybe one the guys who currently working could help out. I dont have wii so dont know how to get logs/crashdump on that device but if you can, please post it.

post also other info, like what the retroarch version was, the fceumm version, the game being tested and if you are loading a new save state or an older one, etc.

**Comment by rogerioronin** [comment]
The "save state" of the libretro-fceumm core never worked on the Nintendo Wii, although in older versions (1.7.2 for example) the "Nintendo Entertainment System" games normally start (except for some games of "Famicom Disk System "), but now almost always the core hangs and consequently the console also hangs, when the libre-fceumm starts a game. And most importantly, the save state does not work!

The problem is that all existing cores of RetroArch for Nintendo Wii have some problem, this is very sad because RetroArch is in many cases the only option to play some specific games on Nintendo Wii!

Sorry for the bad English.

**Comment by retro-wertz** [comment]
last time i worked on issue that affected Wii as well (was only emulating Wii using Dolphin Emu) was back in March. savestates/loadstates should be working as tested with some people using wii/ps3. so probably somewhere between then and now has broken the Wii port, because as you have said it that all existing cores are having problems.

It is probably best to post this issue to main RetroArch repo since it affects other cores as you have said.

**Comment by SuperrSonic** [comment]
[fceumm_wii.zip](https://github.com/libretro/libretro-fceumm/files/2660144/fceumm_wii.zip)
I compiled 4d24c4be4af7515fd4cda2e2a7f2ac1d7254764c and tested on a clean start, what I experienced is that various games will not load a state, however some of them _do_ work fine. The state file does get written to the device but it never loads it, it just resumes the content and it never crashed here. State size is either 301.6 KB or 13.4 KB regardless of it working or not.

Failed [fce_wii_states.zip](https://github.com/libretro/libretro-fceumm/files/2660164/fce_wii_states.zip)
Working [fce_wii_states2.zip](https://github.com/libretro/libretro-fceumm/files/2660165/fce_wii_states2.zip)

I did try to get this working a long time ago but found nothing, no regressions or anything. Thought https://github.com/libretro/libretro-fceumm/issues/191 was the issue but it seems to not matter on GC/Wii. This shouldn't be a RA issue, other cores, the NES cores specifically don't have this issue.

Here are some games that failed to load a state:
Super Mario Bros.
SMB3
DK
Metroid
Mega Man
Kirby's Adventure
Balloon Fight
Zelda 1
Earthbound Zero
Idol Hakkenden
Duck Tales
Princess Tomato

Games where state loading does work:
Metal Slader Glory
Ganbare Goemon Gaiden 2
Famicom Detective Club Part I & II

**Comment by retro-wertz** [comment]
@SuperrSonic see if any of these commits work:
- https://github.com/libretro/libretro-fceumm/commit/16170cdfa741e5e0f41adce5d1c379314407126a
this is a commit after fix to this issue at least https://github.com/libretro/libretro-fceumm/issues/191
smb should be working the very least
this is also a PR before adding save states were changed for the input delat stuff.

- https://github.com/libretro/libretro-fceumm/commit/e3362d3772eb8f16826597fb87a827edeb44a5a1
these is a later commits i did that also affects states but only for specific mappers (vrc6, 19,163, something that uses expansion audio)

- see also if using high/higher audio vs low quality in core settings makes a difference (need to restart core for each change)

in any case i dont have Wii or B-E stuff to work on (cant seem to compile wii stuff in arch atm and running on dolphin is just really slow on my system)

**Comment by retro-wertz** [comment]
thanks for the reply. each version you need to make new savestate though since any changes to them would make it incompatible with each other. are you loading the states from the last version? they would problems for sure if thats the case.

**Comment by SuperrSonic** [comment]
Yeah, that did solve the problem, it seems that saving over old states is not enough and in Zelda 1's case I had to delete the save as well.

I narrowed it down to https://github.com/libretro/libretro-fceumm/blob/master/src/sound.c#L1203-L1228, remove this and the states will load, but will break state loading in some games (Metal Slader, Famicom Tantei).

**Comment by retro-wertz** [comment]
> Yeah, that did solve the problem, it seems that saving over old states is not enough and in Zelda 1's case I had to delete the save as well.
> 
> I narrowed it down to https://github.com/libretro/libretro-fceumm/blob/master/src/sound.c#L1203-L1228, remove this and the states will load, but will break state loading in some games (Metal Slader, Famicom Tantei).

its probably more than just those entries thats causing the issue, since the states you previously sent have missing states entries while others are oversized up to 301.6KB for some reasons (although big-endian issues are to be blames here as well)

(avoid for now games that has expansion audio like Metal Slader (MMC5) since those as well have its own save states vars in its mappers that potentially a problem to big-endian)

if you can, please send in new savestates of games that were in the previous states you attached and which ones are working and which are not.

**Comment by SuperrSonic** [comment]
Sorry, I just realized something I somehow missed while testing, even if the states load, be it the latest version or 16170cd if I exit RA then the next time I load a state it will ignore it and just resume/unpause. In other words the states only work during the session they were created in.

If you still need new states should I get them from 16170cd ?

**Comment by retro-wertz** [comment]
> Sorry, I just realized something I somehow missed while testing, even if the states load, be it the latest version or [16170cd](https://github.com/libretro/libretro-fceumm/commit/16170cdfa741e5e0f41adce5d1c379314407126a) if I exit RA then the next time I load a state it will ignore it and just resume/unpause. In other words the states only work during the session they were created in.
> 
> If you still need new states should I get them from [16170cd](https://github.com/libretro/libretro-fceumm/commit/16170cdfa741e5e0f41adce5d1c379314407126a) ?

there have been a few minor changes that may or may not improve states in wii on the latest version. you can try the latest commits. if it still have issues, please re-submit states at least based on the game titles you already have tested and posted earlier. I would also like to request if you can to test also Lagrange Point and send in state file as well regardless of it worked or not(of course state if they do work or not)

and i they still are a problem in latest version, please test in https://github.com/libretro/libretro-fceumm/commit/16170cdfa741e5e0f41adce5d1c379314407126a commit and send in states as well. 

please do test in a fresh and clean states folder. thanks.

**Comment by SuperrSonic** [comment]
latest [nes_states.zip](https://github.com/libretro/libretro-fceumm/files/2673135/nes_states.zip) and [16170cd.zip](https://github.com/libretro/libretro-fceumm/files/2673461/16170cd.zip)

Lagrange Point loads states and I even managed to load it after a core restart. Just like with Zelda 1 I also had to delete the save file when making a new state to avoid visual glitching.

**Comment by retro-wertz** [comment]
this is very inconsistent. some chunks are missing while others have too much.

**Comment by retro-wertz** [comment]
A PR has been pushed to fix most if not all of state-related problems. Only a few common roms from the most common mappers, including those with expansion audio has been tested just enough to see if those loads the states after restarting retroarch.

These said fixes affects Wii / WiiU and GC (based on what was defined as GEKKO, and not MSB_FIRST). To be confirmed if similar problems are also experienced in other big-endian platforms.

**Comment by rogerioronin** [comment]
Thanks for the help with FCEUmm "save state" problem!

**Comment by hizzlekizzle** [comment]
Is this issue resolved? (big thanks to @retro-wertz for his work on this either way)

**Comment by rogerioronin** [comment]
So far, every game I've tested works the "save state" correctly!

Many thanks for the cart with the Nintendo Wii that lately is a little abandoned, an example of abandonment is the core Snes9x2002 never worked on Nintendo Wii, and this core would be of great use since it is lighter than the others!
