### ISSUE TITLE
Can not open game from Cah4e3

### ISSUE THREAD

**Issue by Mulder97** [libretro/libretro-fceumm#254]
Hello, please sometimes add support for 90-in-1 Hwang Shinwei (Unl) [U] [!]
Thank you for your work
Have a nice day
Thank you for your response
Mulder

**Comment by Leonyd10** [comment]
The emulator has little support for the mappers
Not Open
200 in 1 Retro TV Game (VT02) Mapper 256
16-in-1 (SA005-A)(Unl) Mapper 255
19-in-1 (k-3088) (810849-c) (unl)
21-in-1 (K-3006)(Unl)
35-in-1 (k-3033) (6-15-c) (unl)
Teletubbies Y2K (420-in-1) Mapper 237
Super Game 143-in-1 (The Best Games Of NES)(Mindkids)(Unl)
31-in-1 (3150) Mapper 360
1995 Super HiK 4-in-1 (JY-016) Mapper 91
1996 Power Rangers HiK 4-in-1 (JY-066) Mapper 281
1996 Soccer 7-in-1 (JY-014B, rev0) Mapper 295
1996 Super Aladdin III 18-in-1 Series (JY-064) Mapper 282
1996 Super HiK 3-in-1 (JY-068) Mapper 281
Super Boy Top 5-in-1 Mapper 359
Super Mario Family Mapper 353
Maybe it will be lucky, and other updates will include these extra mappings :-)
Thank you in advance

**Comment by Leonyd10** [comment]
https://wiki.nesdev.com/w/index.php/J.Y._Company_ASIC
https://wiki.nesdev.com/w/index.php/NES_2.0_Mapper_274
Here are the codes

**Comment by retro-wertz** [comment]
duplicate https://github.com/libretro/libretro-fceumm/issues/252

**Comment by Mulder97** [comment]
What duplicate ?? I do not know that man.
There's probably more to us than they want a similar thing

**Comment by Mulder97** [comment]
You could at least write off the topic

**Comment by retro-wertz** [comment]
please see what "duplicate" means.

**Comment by Mulder97** [comment]
I do not know [Leonyd10] user

**Comment by Mulder97** [comment]
retro-wertz

please add support 90-in-1 Hwang Shinwei (Unl) [U] [!]

**Comment by Leonyd10** [comment]
HI Thank you for answer
How are you?

Where are you from?


ne 10. 2. 2019 v 13:23 odesílatel bparker06 <notifications@github.com>
napsal:
