### ISSUE TITLE
Broken libretro input code

### ISSUE THREAD

**Issue by kivutar** [libretro/libretro-fceumm#255]
fceumm and mednafen_supergrafx are the two only cores that require the frontend to explicitly set a RETRO_DEVICE_JOYPAD on port 0 to accept inputs.

libretro.h states:

```
/* Sets device to be used for player 'port'.
 * By default, RETRO_DEVICE_JOYPAD is assumed to be plugged into all 
 * available ports.
 * Setting a particular device type is not a guarantee that libretro cores 
 * will only poll input based on that particular device type. It is only a 
 * hint to the libretro core when a core cannot automatically detect the 
 * appropriate input device type on its own. It is also relevant when a 
 * core can change its behavior depending on device type. */
RETRO_API void retro_set_controller_port_device(unsigned port, unsigned device);
```

Does this mean that the core must expect the frontend to set a RETRO_DEVICE_JOYPAD on each ports?
Or does it mean that the frontend can expect the cores to assume a RETRO_DEVICE_JOYPAD when nothing is specified?

**Comment by retro-wertz** [comment]
i have made both input for both cores. whats the problem? does input not work? in most cases, core should have same defaults, which means something like a SUBCLASS of RETRO_DEVICE_JOYPAD, but for the case of fceumm, it should start(when config is joypad is in auto) to start whatever the game supports (through matching crc)

**Comment by fr500** [comment]
It's not really a problem other than API compliance.
The problem is most cores are modeled after RetroArch behavior, not really the API, and I figure @kivutar is having some issues on his new frontend.

**Comment by retro-wertz** [comment]
i think forcing input_type[2] == RETRO_DEVICE_JOYPAD at init /retro_load_game should remedy this, assuming frontend would somehow skip running retro_set_controller_port_device()

**Comment by negativeExponent** [comment]
is this still broken?
