### ISSUE TITLE
PS3 Save states not working

### ISSUE THREAD

**Issue by goldug** [libretro/libretro-fceumm#280]
Hello.
For more than a year now, save states haven't been working for me when using the fceumm core in RetroArch for the PS3.
I've looked around and it seems that others don't have this problem for some reason...
I've tried reinstalling retroarch, updating the core, wiping all configurations and still no change.
I'm using the latest version of RetroArch.
The interesting thing is that cheats work for fceumm core, but not quicknes. However, save states does work on the quicknes core. The nestopia core doesn't work at all.

I'm running retroarch on a CEX-PS3.

**Comment by goldug** [comment]
Accidentally pressed the close issue button...

**Comment by retro-wertz** [comment]
sadly i dont have access to test for ps3, i did fix a few states problem on wii port which were mostly endian issues. are you by any chance able to compile for ps3?

**Comment by retro-wertz** [comment]
Hi. im pushing a PR. hopefully this helps PS3 savestates, this will in turn make previous invalid, so if you have any important save states, save them for now.

https://github.com/libretro/libretro-fceumm/pull/282

**Comment by goldug** [comment]
That fixed it! Thank you so much!

**Comment by goldug** [comment]
Hmm, the problem is back after some update. Don't know which one though...

**Comment by twinaphex** [comment]
Make it very clear for which mappers this is.

**Comment by goldug** [comment]
> 
> 
> Make it very clear for which mappers this is.

I think it's for all of them. At least mapper 4 I think (Little Nemo). Gonna test other games later today, if I have time.

**Comment by negativeExponent** [comment]
this is now fixed in latest commit. this can now be closed.

@twinaphex
