### ISSUE TITLE
Unif bmc-830013-b

### ISSUE THREAD

**Issue by MILANEK11** [libretro/libretro-fceumm#283]
Support Unif bmc-830013-b Mapper 274 Fceumm (SVN) bb8aef8
Core update Fceumm (SVN) c2a432f  
it freezes and does not open
:-(((((
Please correct the error, thank you very much

**Comment by MILANEK11** [comment]
Or where can I download the older version? Fceumm SVN bb8aef8 PS3 Self type
Thank you very much

**Comment by retro-wertz** [comment]
done. this should be fixed on next update.

**Comment by MILANEK11** [comment]
Thank you very much

**Comment by MILANEK11** [comment]
Please add Mapper 282, 295,BMC-Super24in1SC03,369, 269,360

**Comment by hizzlekizzle** [comment]
Alright, the original issue is fixed, so I'm closing this issue.
