### ISSUE TITLE
Troll Burner won't start

### ISSUE THREAD

**Issue by keithbowes** [libretro/libretro-fceumm#300]
When I tried the Troll Burner demo from the [The New 8-Bit Heroes site](http://www.thenew8bitheroes.com/) with this core, all I got was a gray screen.  I thought about trying to backport Mapper 30 when I discovered it's already implemented, so I tried the Mystic Origins demo mentioned in the comments of src/boards/unrom512.c and it worked fine, as did the bundle of user-contributed ROMs from the New 8-Bit Heroes site.  It seems that it's a problem that only occurs with this one game, but I can't find any diagnostic information to figure out why.

**Comment by hizzlekizzle** [comment]
That's weird. retrowertz definitely tested troll burner when he added that mapper :/

**Comment by negativeExponent** [comment]
your copy is probably does not have battery bit enabled. that or either you already have a savefile for the rom which causes problems.

here is what my rom looks like

[libretro INFO]  ROM CRC32:  0x1ce7e290
[libretro INFO]  ROM MD5:    0x8e2db69e3c6ad503fd43aa1739a7dd61
[libretro INFO]  PRG ROM:   32 x 16KiB
[libretro INFO]  CHR ROM:    0 x  8KiB
[libretro INFO]  Mapper #:  30
[libretro INFO]  Mapper name: UNROM 512
[libretro INFO]  Mirroring: Vertical
[libretro INFO]  Battery-backed: Yes
[libretro INFO]  Trained: No
[libretro INFO]  CHR-RAM:   32 KiB
