### ISSUE TITLE
Update Fceumm

### ISSUE THREAD

**Issue by Leonyd10** [libretro/libretro-fceumm#301]
hello, when will the new update?
Hundreds of mappings are missing.
other emulators add mappers every now and then ( Nintendulator, Nestopia Plus)
Perhaps we will not be left behind with such little mapping support
Thank you for understanding

**Comment by Leonyd10** [comment]
I forgot to point out yet
fceumm is missing the Soft and Hard Reset functions to switch multicart menu

**Comment by hizzlekizzle** [comment]
Closing as duplicate of #290
