### ISSUE TITLE
Fceumm Mappers, NO DUPLICATE!!!!

### ISSUE THREAD

**Issue by Leonyd10** [libretro/libretro-fceumm#302]
Hello, i'm no duplicate
Why do you think that only one person wants to add mappers? That's bullshit
There are a lot of people who want it to play these games
So don't throw me in the bag with the others

**Comment by hizzlekizzle** [comment]
I'm not saying _you're_ a duplicate, though the complete lack of github activity and similar language patterns strongly suggest it. I'm saying the issue is a duplicate.

closing as duplicate of #290

**Comment by Leonyd10** [comment]
Ok im sorry, 
I can not speak English very well
Will you add mappers in the future?

**Comment by hizzlekizzle** [comment]
I won't, but someone else may decide to. We would merge it if someone submitted it.

**Comment by Leonyd10** [comment]
ok, thank you for your reply, i paid to add mappers to the chinese man, but i was robbed. I have to find someone else. I copied my multicart but I can't open it in Fceumm. Missing Mappers 391, 134,52, 319 , 213 :-(

**Comment by Leonyd10** [comment]
hello, how to put my wish into reward?Bouny Source. I don't know how to pay the reward.
