### ISSUE TITLE
Interest in a PPU memory map?

### ISSUE THREAD

**Issue by JoeOsborn** [libretro/libretro-fceumm#303]
I do a lot of academic research that examines how games operate at the console level, so I need access to low level game hardware state.  I would like to access both NES RAM and PPU RAM through the libretro memory map interface, so I imagined adding four memory descriptors:

1. PPUREG, mapped at $2000, whose pointer would point to a copy of the four bytes in PPU plus the result of ARead[...]-ing bytes 2004–2007.
2. NTARAM, mapped at $2000–2FFF
3. PALRAM at $3000
4. OAM at $4000, or maybe at 0.

It could also make sense to use 1<<63 as a select bit so the addresses would be e.g. 1<<63 | 0x4000 to get the first bytes of OAM. 

I’m happy to implement this change if it could be accepted relatively quickly.  Does that seem possible?

**Comment by twinaphex** [comment]
Sure, that sounds alright to me.

**Comment by JoeOsborn** [comment]
Cool!  I’ll append them to the other descriptors.  Is the “64” max descriptor count an arbitrary bound or are there mappers with 64 blocks of memory to map?  In other words should I bump that 64 up to 68?
