### ISSUE TITLE
Nazo no Murasamejou (Japan) (FDS) works headerless, but not headered

### ISSUE THREAD

**Issue by Sanaki** [libretro/libretro-fceumm#305]
The header is identical to that of other games that run fine in this core. Manually removing it allows the game to work without triggering error 25. The same game runs in mesen as well. Not really sure what's going on here,

Game with header:
CRC32: 2acde825
MD5: aa4d8cb4d587b6234387b62e651f2419

Game without header:
CRC32: 9a523757
MD5: fa04b0b2d99d560e7076198ab72a15d3

Header: 46 44 53 1A 02 00 00 00 00 00 00 00 00 00 00 00

**Comment by negativeExponent** [comment]
are you soft-patching by any chance? 'coz both works fine on my end.

![Screenshot_2019-11-10_17-57-21](https://user-images.githubusercontent.com/54053706/68542102-a93c9200-03e3-11ea-8722-981772aa0be6.png)

**Comment by Sanaki** [comment]
My mistake, I know what happened and got it sorted. I had unintentionally launched the game with a matching ips while setting up to convert it to a headered patch and that (flawed) version was saved. I forgot about the save system used by floppy emulation.
