### ISSUE TITLE
 How do I put my message in BOUNTYSOURCE?

### ISSUE THREAD

**Issue by lijud222** [libretro/libretro-fceumm#306]
I would like to add a few mappers to fceumm, I don't know how to put them in the BOUNY SOURCE. I will pay the reward, please for help.

**Comment by hizzlekizzle** [comment]
Take the URL of the issue that explains what you want (probably this one: https://github.com/libretro/libretro-fceumm/issues/252) and then go to bountysource.com and hit the button to create a new bounty. It will bring up a window where you can post in that URL and it will tie the bounty to the issue.

**Comment by lijud222** [comment]
Thank you so much, I'm going to try. No 252, I need other mappers.
You are so kind

**Comment by lijud222** [comment]
#307 

I put in a $ 50 reward¨
Thank you

**Comment by Leonyd10** [comment]
Hizzlekizzle : Do you think there's a chance someone adds mappers? Or $ 50 Is Little? :-(

**Comment by Leonyd10** [comment]
Hizzlekizzle : Do you think there's a chance someone adds mappers? Or $ 50 Is Little? :-(

**Comment by lijud222** [comment]
Hizzlekizzle : Do you think there's a chance someone adds mappers? Or $ 50 Is Little? :-(

**Comment by hizzlekizzle** [comment]
I couldn't say. It depends entirely on who wants to work on it.

**Comment by lijud222** [comment]
Oh, I guess nobody can. Missing Retrowertz :-(
