### ISSUE TITLE
Raw cheat code support 

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/libretro-fceumm#312]
RetroPie 4.5.1

Raspberry pi 3b+

RetroArch 1.8.2

Windows 10

Is there a chance we may be able to see Raw cheat code support? I have so many raw cheat codes that I would love to use on this emulator

code example

Legend of Zelda, The (USA) (Rev A) Infinite Bombs code 0658:08 I put that code in and it does not work. I tried it on the Windows version on fceumm it works.

**Comment by negativeExponent** [comment]
RA's cheat engine should work with RAM-based cheats (not wram ones though, yet)

**Comment by Cibomatto2002** [comment]
Sorry I forgot to say this is where I got my copy of the Windows port of fcemm.

https://www.emutopia.com/index.php/emulators/item/289-nintendo-nes-famicom/126-fceumm

I'm not sure how to add codes with the RA's cheat engine I will try to find a guide on this.

**Comment by negativeExponent** [comment]
i think this can be closed since the issue is related to RA Cheat Engine.

**Comment by Cibomatto2002** [comment]
I found another nes core that works with cheats better. Thanks for your time.
