### ISSUE TITLE
 adding more new mappers

### ISSUE THREAD

**Issue by lijud222** [libretro/libretro-fceumm#319]

**Comment by lijud222** [comment]
Hello, can I send you more new mappers to add?
Multicart are public from http://masterdisk.byethost15.com
In about 14 days
Thank you for your response

**Comment by lijud222** [comment]
And three mappers still don't work, they need to be fixed

**Comment by negativeExponent** [comment]
you are breaking policy here...

**Comment by lijud222** [comment]
Why? You have written to make a request, and that is what I am doing now.
There is nothing wrong with adding a mapper. On the contrary, it's great to have more support.

**Comment by lijud222** [comment]
Add more mappers when my friend writes them?

**Comment by NRS-NewRisingSun** [comment]
Since we cannot know which mappers were even requested before the description was removed, this issue should be closed.
