### ISSUE TITLE
FCEUmm not recognizing save files

### ISSUE THREAD

**Issue by ABeezy13** [libretro/libretro-fceumm#330]
Hello,

I use the FCEUmm core within Retroarch (also use retro achievements) and I have several different NES saved game files (.srm, not save states). I just recently built a new pc. However, on my previous/old pc I was in the middle of playing Zelda II (Also have a full completed save for Zelda I) and when I load the game on the new pc threw Retroarch and the FCEUmm core it keeps giving me a fresh .srm save file overwriting my file and then is a new game.

I have verified I am using the correct path where my saves are and all my other cores are properly working and recognizing my saves and loading them when I play a rom/game. Both Zelda I and II have built in saved game features that allow for 3 saves within each game. I have used this feature and on my old pc and like above have no problem loading the game and continuing my save. However now on this pc is overwrites my game and save file. When I navigate to the save game folder in my file structure the game shows a present date and time stamp and wipes my game from exsistance.

I have a copy of my save that I keep dropping into the save game folder and then overwritting the "new" game and everytime I re-open FCEUmm and my Zelda games in particular it overwrites them yet again. 

I have no idea what is causing this and am looking for some help resoling this. 

I am currently running Retroarch 1.8.4 on Windows 10
I am currently running FCEUmm ((SVN) aba448a)
I have also attached both of my Zelda .srm files 

Thank you in advance for the help!
[ZELDA .SRM SAVES.zip](https://github.com/libretro/libretro-fceumm/files/4271075/ZELDA.SRM.SAVES.zip)

**Comment by negativeExponent** [comment]
after checking, this seems to happen on NES 2.0 headered roms. looks like some of these nes 2.0 roms have incorrect work ram size that causes battery save files from being written correctly.
this should be fixed in proposed PR by overriding battery save size and work ram size for known games and ignore these info from nes 2.0 headered roms.

**Comment by ABeezy13** [comment]
FCEUMM has been updated per conversation with @negativeExponent . Updated my core in Retroarch and saves are now loading and working properly.
