### ISSUE TITLE
Mario Adventure shows black screen on Raspberry Pi

### ISSUE THREAD

**Issue by vanfanel** [libretro/libretro-fceumm#34]
This hack is considered one of the best hacks on the NES ever.
http://www.romhacking.net/hacks/70

It's a whole new Mario game, based on Super Mario Bros 3.
The game works fine on libretro-fceumm on my X86_64 desktop linux pc, but fails on the Pi with the same core: music plays but it only shows a black screen.

**Comment by MightyPrinny** [comment]
Try with another rom, the one i'm using has been patched for running on real hardware and also fixed this same problem on my 3ds.

**Comment by meepingsnesroms** [comment]
The developer of mario adventure only tested with an emulator and later found out they used emu specific bugs in the game.(Something to do with mappers)
