### ISSUE TITLE
Zapper detection spread?

### ISSUE THREAD

**Issue by arpruss** [libretro/libretro-fceumm#354]
I could be mistaken, but my feeling is that given the analog way the original zapper worked, it would probably detect a target flash even if it was pointed a few pixels away from the flashed area. I think it was not a single-pixel-precision device. 

But a more modern lightgun can have higher precision (e.g., I use a Wiimote with four custom mounted IR LEDs spread around the TV and homography calculations to get a high precision pointer) and will detect a target flash only if it is pointed right at a pixel in the target area. If I am right, this means that you need to aim much more precisely to hit a target flash, making the games harder. I am wondering if one could make the fceumm zapper code detect target flashes in an adjustable area around the lightgun or touchscreen touch, allowing target hitting with lower precision, and thus more accurately replicating the original experience.

I could be wrong about the original experience, since I don't actually have an original zapper.

**Comment by arpruss** [comment]
I was mistaken: there is a 4 pixel fuzz factor in the fceumm code. But I think it would be good if it were adjustable.

**Comment by hizzlekizzle** [comment]
Well, that's good. That should make it significant easier to turn into a user-configurable option.

**Comment by arpruss** [comment]
I'll submit a PR that makes it user-configurable shortly.

**Comment by arpruss** [comment]
Done: https://github.com/libretro/libretro-fceumm/pull/356

**Comment by negativeExponent** [comment]
Try to test using this zapper test rom is this is what you expected:
[zapper_light [a2].zip](https://github.com/libretro/libretro-fceumm/files/4584503/zapper_light.a2.zip)

from my test, i don't think you need the rounding as the zapper seems to have a good tolerance around the corners. Also exposing a 32 px offset is kinda making things very easy (check the gap in the test rom) might good for people with very fat fingers and very small touchscreens. FCEUmm's zapper uses tolerance of 4 pix, the Shadow Gun 7, some emu use offset of 8 while Mesen has no tolerance at all.

**Comment by arpruss** [comment]
The fceumm zapper has a tolerance distance of 5.7 pixels at corners (= 4 diagonal pixels * sqrt(2)) and 4 pixels at the sides, because its tolerance region is rectangular. This is unrealistic, since from the photos I've seen, the original NES Zapper had a round lens focusing light into the sensor, and hence had no more tolerance at corners than at the sides of the target--in fact, I expect it had a bit less tolerance at the corners since there will be a smaller proportion of white light when it's pointed at the corners (a pie slice rather than a near semi-circle). So, a rounded tolerance region is more realistic.

I agree that exposing 32px makes things very easy, but it will be nice for small children, and it's in the spirit of emulators allowing cheats. :-) Moreover, how hard things are will depend on factors such as size of screen, distance from screen and pointing/gun hardware, so having more adjustment range is good. 

The default setting in my PR is 6, which gives the same tolerance as stock fceumm at the corners, but two pixels more at the sides. 

I could add a toggle between rounded and rectangular tolerance regions, but I don't really see any advantage of the rectangular tolerance region.

BTW, for my testing, I have crosshairs turned off in fceumm and I am using a Wii remote with four custom infrared LEDs trapezoidally mounted around the edges of the TV and using custom calibration code (https://github.com/arpruss/cwiid/blob/master/map.py). The Wii remote has pretty decent built in "iron sights" (namely, one can visually align the 1/2 buttons with middle of the dpad). This gives pretty good precision on our 43-inch TV, but it's still really hard for my 7-year-old to hit anything in Duck Hunt with the stock fceumm settings. And clay shooting in Duck Hunt and To The Earth feel too hard for me with stock settings, though maybe they're really supposed to be this hard (I have to confess to never having played the originals). I feel that with my rounded tolerance region, a good setting for a good balance between fun and challenge is probably about 7-10.

**Comment by arpruss** [comment]
My PR fixing this has been accepted, so I am closing.
