### ISSUE TITLE
issue with handling ':' char or 6-character GG codes

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/libretro-fceumm#378]
Most cheat codes I try do not work for fceumm. The emulators  Mesen and Nestopia all my cheat codes work here is a example code that does not work on fceumm.

Legend of Zelda, The (USA) (Rev 1)
 
Cheat: 0658:08

Description: Inf. Bombs

**Comment by negativeExponent** [comment]
works fine on my end.
![cheat](https://user-images.githubusercontent.com/54053706/91670771-0c560b80-eb53-
11ea-8152-4868a6968936.png)

**Comment by Cibomatto2002** [comment]
I forgot to add I'm on a pie 4 and using lakka

**Comment by negativeExponent** [comment]
so its not a core issue then.

**Comment by Cibomatto2002** [comment]
i also tried on Retroarch 1.9.0 and still do not work for me what are you using? Can you try it on Retroarch 1.9.0 and see if you get them to work?

**Comment by Cibomatto2002** [comment]
I thought it was a core issue sorry about that.

**Comment by negativeExponent** [comment]
im on latest commit of RA, using linux. im using the ra engine cheats search thing (whatever that is called).
there is a code in the the preset cheat files method to be used with core engine (cheat #98) on the list, and that did not seem to work. So, there is probably and issue with handling ':' char or 6-character GG codes in general. To add to add, core does not support multi-lined cheats.
Can you reopen and rename the title to match the issues?

**Comment by Cibomatto2002** [comment]
I uploaded my Retroarch cheats that I know will work with  Mesen and Nestopia most do not work with fceumm.



[RetroArch Mesen and Nestopia cheats.zip](https://github.com/libretro/libretro-fceumm/files/5147755/RetroArch.Mesen.and.Nestopia.cheats.zip)

**Comment by negativeExponent** [comment]
- ok, cheats with ':' or 6-digit cheats does not have to do through the decoder, but have to filter out ':' and then passed to the cheat handler (2-bytes address, 1 byte data)
- 6-character codes (all letters, no ':') are expected to go through the decode
- still need to do multi-line cheats

**Comment by negativeExponent** [comment]
Push PR to address the handling of these raw cheat formats. There are still issue with regards to pro action replay codes though, cant find something that works.

as far as this issue though, PR should fix it.

**Comment by negativeExponent** [comment]
also fixed PAR code handling, which is just decoded gamegenie code in disguise and pushed an issue where some codes are incorrect, specifically some 8-digit codes, PAR stuff

https://github.com/libretro/libretro-database/issues/1086

**Comment by Cibomatto2002** [comment]
Thank you so much for taking the time to fix this. I wonder why it took so long for someone to post this bug? Shurly I was not the first person to notices this.

**Comment by negativeExponent** [comment]
i really have no clue. there are probably talks about it on discord or other media sites, but issues are just gonna get buried when not posted in github or something.
also no one probably looked close regarding issues and just brush them off as bad codes or something.
i did some work on the core but i dont use cheats so i never noticed any problems with it.

**Comment by Cibomatto2002** [comment]
I just tried the game Life Force some of the codes do not work.

Inv. P1 0084:C0

Always Have Option P1 0091:01

Both codes with in Mesen and Nestopia


[Life Force (USA).zip](https://github.com/libretro/libretro-fceumm/files/5156685/Life.Force.USA.zip)
