### ISSUE TITLE
Problem running ROM's from the command line

### ISSUE THREAD

**Issue by hackneyc** [libretro/libretro-fceumm#383]
When I run a NES ROM from via runcommand.sh it works fine, but if I copy the exact command line from /etc/shm/runcommand.log and paste it to the command line it does not run.
From what I can tell by looking at the verbose log output, when I run from the command line the ROM, which is a .zip file, is not getting unpacked. The emulator is trying to load the .zip file instead of the .nes file contained within it. When run via runcommand.sh the .zip file seems to get unpacked correctly and the .nes file is run.
What am I missing? Any ideas?

**Comment by negativeExponent** [comment]
i dont even know what runcommand.sh is all about.

**Comment by hackneyc** [comment]
Ok. Maybe ignore that bit of my question. To simplify things, I’m wondering
why when I try to run the emulator it doesn’t seem to be extracting the
.nes file from the .zip file.
If I unzip the .zip file and pass in the .nes file it works.
TIA.

**Comment by negativeExponent** [comment]
are you sure this is a core issue? the frontend (in this case retroarch) is what is handling zip files.

i dunno how or why you want to run from the commandline but running for example command below worked fined.  
`retroarch -L <insert-retroarch-core-folder-here>/fceumm_libretro.so <insert-rom-folder-here/'Zanac (USA).zip'`

**Comment by hackneyc** [comment]
Thanks. Must be something strange on my raspberry pi system. I’ll keep
digging.

**Comment by hackneyc** [comment]
I figured it out. The cache directory specified in the configuration file didn't exist. I guess this causes the unzip to fail and think the zip file is a rom file so the emulator tries to load it directly, which fails.

**Comment by negativeExponent** [comment]
if no core issue, can this be close then?
