### ISSUE TITLE
Some cheats not working

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/libretro-fceumm#384]
In Super Mario Bros. (World) (HVC-SM) the cheat Jump In Midair "AOAUIG" does not work. It does work in Nestopia and Mesen

Here is the cheat file 
[Super Mario Bros. (World) (HVC-SM).zip](https://github.com/libretro/libretro-fceumm/files/5180577/Super.Mario.Bros.World.HVC-SM.zip)

**Comment by negativeExponent** [comment]
this was a mistake on my part. sending fix soon...

**Comment by Cibomatto2002** [comment]
Thanks for spending your time on this and getting it done so fast.
