### ISSUE TITLE
Display aspect ratio should not be 4:3

### ISSUE THREAD

**Issue by arromdee** [libretro/libretro-fceumm#40]
Moved from https://github.com/libretro/RetroArch/issues/2837 on request.

http://wiki.nesdev.com/w/index.php/Overscan

The NES has a pixel aspect ratio of 8:7.  A 4:3 display aspect ratio is only correct if you are using the entire overscan area of 280x240 (which includes areas containing no pixels).  If you are using 240x224, the correct display aspect ratio is 240 * 8/7 / 224 = 1.224 which is about 11:9 or with smaller integers, between 6:5 and 5:4.  In general, the display aspect ratio is going to depend on what overscan you are using.

**Comment by matcarfer** [comment]
Maybe a related issue: https://github.com/libretro/libretro-fceumm/issues/41
