### ISSUE TITLE
Yie Ar Kung-Fu (Japan) (Rev 1.4) not working

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/libretro-fceumm#403]
Yie Ar Kung-Fu (Japan) (Rev 1.4) not working on fceumm or the Nestopia UE emulator but the game will work on Mesen Emulator libretro core. Got this log from Mesen Log

------------------------------------------------------
Loading rom: Yie Ar Kung-Fu (Japan) (Rev 1.4).nes
File CRC32: 0x86CEFC12
------------------------------------------------------
[DB] Initialized - 6199 games in DB
[DB] Headerless ROM file found - using game database data.
PRG CRC32: 0xE26A660D
PRG+CHR CRC32: 0x86CEFC12
[iNes] Mapper: 0 Sub:0
[iNes] PRG ROM: 16 KB
[iNes] CHR ROM: 8 KB
[iNes] Mirroring: Horizontal
[iNes] Battery: No
[DB] Game found in database
[DB] Mapper: 0  Sub: 0
[DB] System : Famicom
[DB] Board: KONAMI-NROM-128
[DB] Mirroring: Horizontal
[DB] PRG ROM: 16 KB
[DB] CHR ROM: 8 KB
[DB] Battery: No
[DB] Database info will be used instead of file header.
[Input] 2 standard controllers connected

**Comment by negativeExponent** [comment]
`[DB] Headerless ROM file found - using game database data.`

fceumm and nestopia does not run headerless roms. the internal database is just to correct or used as overrides for bad headers, special flags, etc. Headered roms are still required to play (and should be the case for NES)

**Comment by Cibomatto2002** [comment]
Sorry about that I had no idea it was a Headerless ROM do you know a tool that can scan my roms and fix Headerless ROMS? I had no idea I had any of those. I know Mesen can fix them but  I would have to load up every ROM I had and I got over 700

**Comment by negativeExponent** [comment]
not sure if this will add missing headers:
https://github.com/Kitrinx/NES_Header_Repair/blob/master/nes_header_repair.py

other that that, i dont know of any such tool (using linux here so dunno if there is one for windows).

it would be faster to just get new romsets that clearly states "headered" or better nes 2.0 headered.

you can manually fix them though with existing header database like from nescartdb

**Comment by Cibomatto2002** [comment]
Thank you so much.
