### ISSUE TITLE
Broken Fceumm update for PS3

### ISSUE THREAD

**Issue by ghost** [libretro/libretro-fceumm#407]
When will the current Fceumm update for Playstation 3 be up to date? Or is Fceumm over for the PS3 over? :-((( 
 Last update is from  25 July. Code 0b3c232    Thank you for answer

**Comment by Nesmen89** [comment]
> When will the current Fceumm update for Playstation 3 be up to date? Or is Fceumm over for the PS3 over? :-(((
> Thank you for answer.

**Comment by crystalct** [comment]
https://www.psx-place.com/threads/retroarch-psx-place-community-edition-beta-3.32272/

**Comment by negativeExponent** [comment]
this should now have been fixed in latest commit
