### ISSUE TITLE
Pixel Perfect (Integer Scaling) not working right

### ISSUE THREAD

**Issue by matcarfer** [libretro/libretro-fceumm#41]
Moved from https://github.com/libretro/Lakka/issues/312 and https://github.com/libretro/RetroArch/issues/2837 on request.

Hi, I come from RetroArch (Windows) and using 1920x1080p/60hz over HDMI and Super Mario Bros for NES and every other game I tried using Integer Scaling are Pixel Perfect, no uneven pixels. Its great.

But using Lakka on RPi 2 / Lakka x64 / RetroArch 1.3.3 on Android box (1920x1080p/60hz) and Moto G, NES cores present issues with integer scaling:

Some pixels are wider than others using Integer Scaling On and Bilinear Filtering Off. It's easy to spot as the first "hill" of Super Mario Bros (NES) has uneven pixels.

This occurrs with both FCEUMM and NESTOPIA cores.

Pics: 
Bad Lakka x64: https://i.imgur.com/erGK8pb.jpg
Bad Android: https://i.imgur.com/uQlGJfh.png
Bad MotoG: https://i.imgur.com/jiiPB42.png
Good RetroArch Windows: https://i.imgur.com/V20D5JP.jpg

**Comment by matcarfer** [comment]
Will try other console cores (SNES and MD) later and report.

**Comment by matcarfer** [comment]
Maybe a related issue: https://github.com/libretro/libretro-fceumm/issues/40

**Comment by retro-wertz** [comment]
this probably is solved by the addition of 8/7 aspect ratio  optional vertical/horizontal cropping.

**Comment by hizzlekizzle** [comment]
Alright, I'll close this out and matcarfer can reopen if needed.
