### ISSUE TITLE
[Feature Request] Mapper 342 support

### ISSUE THREAD

**Issue by SumavisionQ5** [libretro/libretro-fceumm#428]
The designer of the Coolgirl board provided an FCEUX source code file, so can anyone get it supported?

[coolgirl.zip](https://github.com/libretro/libretro-fceumm/files/5938942/coolgirl.zip)
https://forums.nesdev.com/download/file.php?id=15348&sid=8396840a81c23fc6178919536c7b4433

Mappers's wiki page: https://wiki.nesdev.com/w/index.php/NES_2.0_Mapper_342

**Comment by SumavisionQ5** [comment]
Got it working, I'll make a PR soon. So close it.

**Comment by NikolkaMedova** [comment]
hello, will you be adding soon?
