### ISSUE TITLE
Obscure Retroarch-PSP + fceumm bug: step by step evidence

### ISSUE THREAD

**Issue by eugene-s-nesdev** [libretro/libretro-fceumm#430]
I have found very interesting and obscure bug
on Retroarch PSP + fceumm. 

In short words:
- if retroarch-salamander.cfg 
contains "fceumm_libretro.PBP" as primary core,
then fceumm's Region Selector doesn't work properly.  

Step by step evidence:
- install retroarch psp, use lastest fceumm_libretro.pbp (91ccd3b)
- make sure retroarch-salamander.cfg contains:
`libretro_path = "ms0:/PSP/GAME/RETROARCH/CORES/fceumm_libretro.PBP"`
- go to the core options, and Force region to PAL or Dendy system
- When you'll run first NTSC game, region selector will work normal and will switch to force PAL or Dendy. 
But when you'll load another NTSC game - it will run at NTSC-mode until you're load PAL game. 
In short words, the region selector works like auto-mode.

But if you're use old fceumm core (0b3c232 commit for example), this bug doesn't happen.  

**IMPORTANT**:
- if retroarch-salamander.cfg 
contains another other core as primary: 
`libretro_path = "ms0:/PSP/GAME/RETROARCH/CORES/fmsx_libretro.PBP"`
then fceumm's Region Selector DOES work properly on lastest commit (91ccd3b) too.   

All configs here:
[all_info.zip](https://github.com/libretro/libretro-fceumm/files/6056610/all_info.zip)

By the way, maybe this is Retroarch bug. 
But i guess it's fceumm bug because nestopia work good, even if retroarch-salamander.cfg
contains:
`libretro_path = "ms0:/PSP/GAME/RETROARCH/CORES/nestopia_libretro.PBP"`

**Comment by negativeExponent** [comment]
are you able to compile the core yourself? if so, can you add this in src/drivers/libretro/libretro.c and compile:

in line https://github.com/libretro/libretro-fceumm/blob/master/src/drivers/libretro/libretro.c#L2378, can you add:

```opt_region = 0;``` after ```dendy = 0;```

so it becomes

```
dendy = 0;
opt_region = 0;
```

this would force the region overrides to activate each time you load a new rom without switching from another core. see if that works or does anything different.

**Comment by eugene-s-nesdev** [comment]
I can compile libretro-fceumm under ubuntu on native x86/x86_64 machine, but not familiar how to cross-compile it for PSP.

**Comment by negativeExponent** [comment]
is doing the mod does anything bad on the ubuntu compile? if not i can make a PR for it, and just update PSP core when available on buildbot
