### ISSUE TITLE
NES - No controller works on HYPER SPORT/OLYMPIC (JAPAN)

### ISSUE THREAD

**Issue by DjDiabolik** [libretro/libretro-fceumm#439]
I'm using currently retropie on a Raspberry Pi4.
I have updated the core to latest currently and whit this 4 roms the controller it's not works.

Whit all other games all it's works but whit this it's only SELECT and START works.... other for run or jump it's no works.

It's a bug ?

**Comment by negativeExponent** [comment]
Konami Hyper Shot controller support now hooked up to core. If you are using custom rom/patched rom version, just make sure that Player 1/2 is set to Gamepad, Player5 to Konami Hyper Shot. 2-player mode was not tested, but single player works fine. Also implemented a 1-frame interval turbo mode(will be modified later),

**Comment by DjDiabolik** [comment]
> 
> 
> Konami Hyper Shot controller support now hooked up to core. If you are using custom rom/patched rom version, just make sure that Player 1/2 is set to Gamepad, Player5 to Konami Hyper Shot. 2-player mode was not tested, but single player works fine. Also implemented a 1-frame interval turbo mode(will be modified later),

@negativeExponent 

OH... i don't have idea if it's a custom rom or patched. It's the roms included on currently "No-Intro" rom set :)

I also hope I have reported it correctly.... english it's not my best knowledge :)

**Comment by negativeExponent** [comment]
your report is fine. This issue should be fixed in latest commit. Just update fceumm once update is available.

**Comment by DjDiabolik** [comment]
> 
> 
> your report is fine. This issue should be fixed in latest commit. Just update fceumm once update is available.

Oh yeah.... it is pleasant to be useful to the cause ;)
