### ISSUE TITLE
UnHeadered roms no more works... it's a bug or it's never supported ?

### ISSUE THREAD

**Issue by DjDiabolik** [libretro/libretro-fceumm#452]
Recently on my retropie setup (on Pi4 4GB) i have update my NES collection.

Before that i have a old collection (about of one or two years ago) by No-Intro........ i have updated to a recent collection (20210415-054135) and i have reversed all .zip on my retropie setup.

Tryed one games and surprise......... all games of NES it's not anymore works.

After some hours of test i have possibly found a solution....... i have found two different NES Pack. One Headered and second UnHeadered.
I have extract the same game zip from both..... one contain the .nes.... second contain a file .unh.

I have tested the .nes...... works GOOD.

The last test...... i have open the same games zip on my retropie setup and it's contain a file .nes........... at this point i have compared the MD5 of all three file obtained this:
`
File      : Millionaire (Asia) (Ja) (PAL) (Unl).nes
Size      : 49168 bytes
Last write: 24/12/1996 23:32:00
MD5       : 3228829EF49E0187C458071A6B2B471B

File      : Millionaire (Asia) (Ja) (PAL) (Unl).unh
Size      : 49152 bytes
Last write: 24/12/1996 23:32:00
MD5       : D289B296EAF9E56D5108EED59077108C

File      : Millionaire MS.nes
Size      : 49152 bytes
Last write: 25/12/1996 01:32:00
MD5       : D289B296EAF9E56D5108EED59077108C
`

Now.... Millionaire (Asia) (Ja) (PAL) (Unl).nes it's from headerer package and it's works......... the other it's one from unheaderer pack and the seconds it's from my actual retropie nes pack.
I can see it's have the same MD5 of unheadered files and i see all my actual .nes it's not works.............. at this point here it's my question:
It's lr-fceumm not supported the unheader roms ? Or i need to do somethigs to made this works ?

Thanks in advance for anyinfo.........

**Comment by negativeExponent** [comment]
unheadered NES roms should not have been allowed to exist, hence.

**Comment by DjDiabolik** [comment]
> 
> 
> unheadered NES roms should not have been allowed to exist, period.

Lol.. i understand. But before this specific case I didn't know the thing :) in the previous pack it was not specified what I had. Now i see the two different version and make in me some confusion :)

The issue it's resolved... apparently for NES it's needed the headered roms. Other core.... for example atari linx.... apparently can handle the unheadered roms whitout any issue.

**Comment by dankcushions** [comment]
other systems like lynx likely don't have the concept of [mappers](http://emulation.gametechwiki.com/index.php/Nintendo_Entertainment_System_emulators#Mappers). this info isn't kept within NES rom data so must be supplied via the header or some other means.

**Comment by DjDiabolik** [comment]
> 
> 
> other systems like lynx likely don't have the concept of [mappers](http://emulation.gametechwiki.com/index.php/Nintendo_Entertainment_System_emulators#Mappers). this info isn't kept within NES rom data so must be supplied via the header or some other means.

ah ok... thanks for the clarification.

Infact right now i have tryed some headered roms........... and everything is back to work as it always was :)

**Comment by negativeExponent** [comment]
please close if there are no more lingering issue
