### ISSUE TITLE
Family Boxing (Japan) Black screen

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/libretro-fceumm#476]
Family Boxing (Japan) has a Black screen you can here the music playing in America this game is called Ring king. Ring King play correct. Other Emulators play Family Boxing (Japan) correct. nestopia_libretro.dll, mesen_libretro.dll

Family Boxing (Japan) MD5: 48370A705EFBE3F7F171D503769A65A549B9CD91

**Comment by negativeExponent** [comment]
https://nescartdb.com/profile/view/1589

most likely an incorrect header, specifically mirroring bit. fceumm relies heavily on correct header info on most known and licensed games to run. Only rare cases are added in internal database, like those unlicensed ones which are commonly assigned with wrong mappers numbers or games that required nes2.0 header info requirement

**Comment by negativeExponent** [comment]
https://nescartdb.com/profile/view/1589

most likely an incorrect header, specifically mirroring bit. fceumm relies heavily on correct header info on most known and licensed games to run. Only rare cases are added in internal database, like those unlicensed ones which are commonly assigned with wrong mappers numbers or games that required nes2.0 header info requirement

**Comment by Cibomatto2002** [comment]
Should I close ?

**Comment by Cibomatto2002** [comment]
I justed tried the game again if I press start you can play it but most of the backrounds are not there.
