### ISSUE TITLE
Cybernoid - The Fighting Machine (U) 

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/libretro-fceumm#477]
Game has graphics errors This was fixed back in Aug 17, 2016 in Mesen here is the link on how it was fixed.

https://github.com/SourMesen/Mesen/commit/68c4366cc87f01283f6af1d005156c3433996cfb

Mapper 3: Force all games using the NES-CNROM board to use bus conflicts

**Comment by negativeExponent** [comment]
yeah, mapper behavior was changed to no bus-conflicts by default and relies
on Nes 2.0 headers to force bus conflicts. the game itself might not have
been added to internal.database.
if you are able to, you can send pr to update database (as i am not able to
due to limited resources for months....)

**Comment by Cibomatto2002** [comment]
Do you have a link so I can send a pr?

**Comment by negativeExponent** [comment]
add your game after this line here:
https://github.com/libretro/libretro-fceumm/blob/c291ceeb13052ab9812887b0e013c7a52c8c3ed8/src/ines-correct.h#L138

example:
	{ 0x684afccd,    3, 2,    MI_V, 0, DEFAULT, DEFAULT, DEFAULT, NOEXTRA }, /* cybermania something */

you can view ROMs info like crc, mirroring, etc by looking at retroarch logs during loading rom. you will nid the rom crc, set the value of 2 in submapper column, set mirroring in the mirroring column, MI_H for horizontal or MI_V if vertical etc. 

when you done, you can also try adding the other game you had issue with (the boxing game)

**Comment by Cibomatto2002** [comment]
I can't type anything on line 138

**Comment by negativeExponent** [comment]
if you are able to send me the rom information logs from retroarch for this rom and the boxing game one, i may be able to update the database. i may have another time to do it this week or so.

**Comment by Cibomatto2002** [comment]
I don't have the boxing game anymore I got a log from Mesen and Retroarch.

![1](https://user-images.githubusercontent.com/21169038/150647956-605ee1e6-231e-4e5a-a427-26eaccde25b8.jpg)

![2](https://user-images.githubusercontent.com/21169038/150647958-49731671-d188-4389-b8f4-b78ff6c3847b.jpg)

**Comment by negativeExponent** [comment]
should be fixed when this gets merged: https://github.com/libretro/libretro-fceumm/pull/482/commits/a4442631aa47239028240090f2ae262b5686f070

**Comment by Cibomatto2002** [comment]
thanks a lot.
