### ISSUE TITLE
Mapper 176 -  saved state error

### ISSUE THREAD

**Issue by DusanFamicom** [libretro/libretro-fceumm#486]
State saving from mapper 176 ROMs works on PC but fails on other platforms.

**Comment by crystalct** [comment]
Tested on PS3 system:
Save state works correcly, infact file state is correcly saved.
Load state doesn't work (does nothing) for 176 mapper Roms. -> Save state file is read, but then nothing is done.
Load state for other mappers works.....
I know that save state and load state are commands done on Retroarch layer, but i suppose that there is something done on core layer to accomplish those tasks.... where could i see that on fceumm sources?

**Comment by negativeExponent** [comment]
if load state works with other mappers on ps3, and m176/fk23 roms works on little-endian platforms, then 176/fc23 should also work on big endian platforms. nothing stands out that seems incorrect on the mapper side.

what game or games are these? if the state files are created, does it have the same filesize on other platforms? or it could be corrupted. attach the savefiles here though i have no ways to test for big-endian.

**Comment by DusanFamicom** [comment]
All Games Mapper 176 does not work saved state (more than one hundred rom)

**Comment by negativeExponent** [comment]
upload the savefile, as i have requested

**Comment by DusanFamicom** [comment]
There are a lot of Rom Mapper 176 of different sizes to share on LIBG, which should be plenty for testing.

**Comment by negativeExponent** [comment]
IM NOT ASKING FOR ANY ROM. IM ASKING FOR THE SAVE STATE FILE

**Comment by crystalct** [comment]
Test files....

[Super_Game_3-in-1_YH_-_3125.zip](https://github.com/libretro/libretro-fceumm/files/7958454/Super_Game_3-in-1_YH_-_3125.zip)
[Super_Game_3-in-1_YH_-_3125.state.zip](https://github.com/libretro/libretro-fceumm/files/7958466/Super_Game_3-in-1_YH_-_3125.state.zip)

[720 Degrees (USA).state2.zip](https://github.com/libretro/libretro-fceumm/files/7958460/720.Degrees.USA.state2.zip)

**Comment by negativeExponent** [comment]
> Test files....
> 
> [Super_Game_3-in-1_YH_-_3125.zip](https://github.com/libretro/libretro-fceumm/files/7958454/Super_Game_3-in-1_YH_-_3125.zip) [Super_Game_3-in-1_YH_-_3125.state.zip](https://github.com/libretro/libretro-fceumm/files/7958466/Super_Game_3-in-1_YH_-_3125.state.zip)
> 
> [720 Degrees (USA).state2.zip](https://github.com/libretro/libretro-fceumm/files/7958460/720.Degrees.USA.state2.zip)

can you resend the files with the SAVE STATE COMPRESSION set to OFF instead?

**Comment by crystalct** [comment]
Where is that option?

**Comment by negativeExponent** [comment]
open Retroarch > Settings > Saving. look for Save State Compression and set it to OFF. make the state files again and upload them again if it still wont work

**Comment by crystalct** [comment]
File..
[Super_Game_3-in-1_YH_-_3125[PS3_NoCompression_notworking].zip](https://github.com/libretro/libretro-fceumm/files/7958604/Super_Game_3-in-1_YH_-_3125.PS3_NoCompression_notworking.zip)
.

**Comment by crystalct** [comment]
Working file state..
[720 Degrees (USA)[PS3_NoCompression_Working].zip](https://github.com/libretro/libretro-fceumm/files/7958619/720.Degrees.USA.PS3_NoCompression_Working.zip)
.

**Comment by negativeExponent** [comment]
do you have any of these roms to test instead?

![Uploading 1643373427_2022_01_28_20:37:07.png…]()

**Comment by crystalct** [comment]
png not visible

**Comment by crystalct** [comment]
i will search....

**Comment by crystalct** [comment]
File..
[4-in-1 (YH4222) (Unl)[PS_NotWorking].zip](https://github.com/libretro/libretro-fceumm/files/7958719/4-in-1.YH4222.Unl.PS_NotWorking.zip)
.

**Comment by negativeExponent** [comment]
this 

> File.. [4-in-1 (YH4222) (Unl)[PS_NotWorking].zip](https://github.com/libretro/libretro-fceumm/files/7958719/4-in-1.YH4222.Unl.PS_NotWorking.zip) .

the savefile does not look like its mapper 176

**Comment by negativeExponent** [comment]
@crystalct if you are able to compile for PS3, try to compile this from my repo to confirm if states are now working or not. test on new state files. if it still does not work, send the savefile again.

https://github.com/negativeExponent/libretro-fceumm/tree/fix_savestates

**Comment by crystalct** [comment]
i will....

**Comment by crystalct** [comment]
Nope...
[Super_Game_3-in-1_YH_-_3125.[PS3_notworking].zip](https://github.com/libretro/libretro-fceumm/files/7960197/Super_Game_3-in-1_YH_-_3125.PS3_notworking.zip)
.

**Comment by negativeExponent** [comment]
well, nothing stands out for me, as the state file seems complete and as you have said, other mappers loads states fine on PS3 but not on mapper 176 and on this case mapper 260 based on 4-in-1 (YH4222) (Unl)[PS_NotWorking].zip test file

**Comment by negativeExponent** [comment]
@crystalct i have updated my repo. please test if this does anything...

https://github.com/negativeExponent/libretro-fceumm/tree/fix_savestates

use the same roms that you have uploaded above, specifically should be mapper 176 or mapper 260. upload the new savestate files. thanks.

**Comment by crystalct** [comment]
Bingo!!!
176 works....

**Comment by negativeExponent** [comment]
please send state files

**Comment by crystalct** [comment]
260 not works
[Super_Game_3-in-1_YH_-_3125[PS3_Working].zip](https://github.com/libretro/libretro-fceumm/files/7962459/Super_Game_3-in-1_YH_-_3125.PS3_Working.zip)
[4-in-1 (YH4222) (Unl)[PS3_notworking].zip](https://github.com/libretro/libretro-fceumm/files/7962460/4-in-1.YH4222.Unl.PS3_notworking.zip)
.

**Comment by negativeExponent** [comment]
ok lemme check 260. do you have discord probably? add me @negative

**Comment by crystalct** [comment]
260 still doesn't wor
[4-in-1 (YH4222) (Unl)[PS3_notworking].zip](https://github.com/libretro/libretro-fceumm/files/7965732/4-in-1.YH4222.Unl.PS3_notworking.zip)
k

**Comment by negativeExponent** [comment]
> 260 still doesn't work [4-in-1 (YH4222) (Unl)[PS3_notworking].zip](https://github.com/libretro/libretro-fceumm/files/7965732/4-in-1.YH4222.Unl.PS3_notworking.zip)

can you chat in discord now?

**Comment by crystalct** [comment]
I am not at home, right now....

Il dom 30 gen 2022, 12:15 negativeExponent ***@***.***> ha
scritto:

**Comment by negativeExponent** [comment]
ok. Try from this new repo instead.

https://github.com/negativeExponent/libretro-fceumm/tree/fix_states_loading_in_big_endian

**Comment by DusanFamicom** [comment]
Thank you all for your help and your time
