### ISSUE TITLE
Retroachievements not unlocking

### ISSUE THREAD

**Issue by Akezhar** [libretro/libretro-fceumm#49]
Most achievements are working fine but some wont unlock for some reason e.g.

First Hidden Treasure (Vampire Killer) 
Concealed Gold Bag (Vampire Killer) 
Concealed Meat (Vampire Killer)

for Castlevania.

The achievements unlock properly using the RANes emulator from the Retroachievements site, there are probably more achievements that don't work, it would be great if someone could look into it.

**Comment by meleu** [comment]
@Akezhar you should update your RetroArch. The cheevos you mentioned and many others are working just fine after some recent (November 5th) RetroArch fixes.

However there are some cheevos that aren't working with on FCEUmm but works fine in QuickNES core. e.g.:

From Metroid
http://retroachievements.org/Achievement/3507
http://retroachievements.org/Achievement/3509

From Super Mario Bros 3
http://retroachievements.org/Achievement/3509

Maybe @leiradel can give more details about this difference between the cores.

**Comment by leiradel** [comment]
Actually I don't know much more other than what @meleu already said: the FCEUmm and Nestopia cores don't expose the emulated Save RAM properly so the achievements subsystem cannot do its duty.

I'll work with the rest of the libretro team and see if we can fix that, but for now QuickNES seems to support all achievements.

**Comment by meleu** [comment]
@leiradel if you guys need some inputs for tests (e.g.: savestates from fceumm vs. quicknes at the same point), let us know.

**Comment by leiradel** [comment]
@meleu thanks, your help has been invaluable!

**Comment by leiradel** [comment]
@Akezhar I think this issue can be closed?

**Comment by Akezhar** [comment]
Sorry for the late reply but I couldn't test this earlier, it seems that the achievements I had problems with can now be unlocked when using QuickNES as suggested so I think the issue can be closed thanks for putting your time into this.
