### ISSUE TITLE
Negativeexponent - game number 15 regression - Tetris family 19-in-1 (NO 1683)

### ISSUE THREAD

**Issue by twinaphex** [libretro/libretro-fceumm#493]
Hi there @negativeExponent ,

I got a report from someone (@DusanFamicom) that a game no longer works as a result of this commit (see pic below).

The game in question is called 'Gane number 15', 'Tetris family 19-in-1 (NO 1683)'.

![image](https://user-images.githubusercontent.com/1075274/152417950-ab8f7f74-9a59-4943-be16-be26a70ee20d.png)

**Comment by negativeExponent** [comment]
its not a regression, since that game is mapper 403 which was 'just added' the specific information to run that specific game is not on nesdev, and until its available there, i wont add any of it

**Comment by NRS-NewRisingSun** [comment]
I have no idea what "specific information" you are referring to.

**Comment by DusanFamicom** [comment]
https://wiki.nesdev.org/w/index.php?title=NES_2.0_Mapper_403
Information, added, thank you
