### ISSUE TITLE
Mach Rider graphical garbage

### ISSUE THREAD

**Issue by superblobster** [libretro/libretro-fceumm#501]
You can see parts of the road on the sides while turning. That's not supposed to be there.

Here you can see how it looks on a real console: https://www.youtube.com/watch?v=Ai5tTrB3ix8&t=26s

And this is fceumm:
![Mach Rider (E)  ! -220219-213924](https://user-images.githubusercontent.com/60817163/154816671-f1054532-e04b-47c1-92d9-58eb3d17a51d.png)

**Comment by NRS-NewRisingSun** [comment]
This looks like a your ROM file has the "mirroring" field set incorrectly in its NES header. The game needs Vertical mirroring; I get the above picture when I set the ROM header to Horizontal mirroring.

**Comment by NRS-NewRisingSun** [comment]
If you can run Python scripts, use my NES 2.0 Header XML database (https://forums.nesdev.org/viewtopic.php?t=19940) together with Kitrinx' Python script (https://github.com/Kitrinx/NES_Header_Repair) to automatically correct the headers of all your .NES files.

**Comment by superblobster** [comment]
Thanks for the script. I was able to fix it :)
I had no idea about this rom header stuff. I guess it's not a core bug then.
