### ISSUE TITLE
Dendy mode

### ISSUE THREAD

**Issue by eugene-s-nesdev** [libretro/libretro-fceumm#51]
**Hi, libretro-fceumm devs.**

Can you import dendy-mode support from lastest fceux source?
It's actually presents in official FCEUX 2.2.3 as well, as advanced overclock
(Vblank and Postrender overclock both methods are available):
http://savepic.su/7304383.png

Would be nice to see region-selector in core options:

> ntsc
> pal
> dendy

**How autodetect was made in fceux:**
NTSC and PAL modes change automatically depending of romname:

> For PAL, FCEUX will detect the proper choice when loading a ROM and set the flag accordingly (based on file name, where (E) is used by GoodTools to mark European ROMs). Dendy mode (sometimes also called Hybrid) is a modification of the NTSC one, it was used in some Famiclones and supports games released for the NTSC region, slowing them down to PAL speed.

When user select Dendy-mode it will force and override NTSC until you load PAL-rom.

**P.S: Region test roms:**
test rom 1: http://forums.nesdev.com/download/file.php?id=2826 (http://savepic.ru/7604789.png) *
test rom 2: http://forums.nesdev.com/download/file.php?id=6415 (it show NTSC/PAL/Dendy region on bottom right, also you can look at "cpu clock speed" test: http://savepic.su/7409612.png *
- \* screenshots from nestopia.

cycles/line and cpu speed will show a bit lower values on fceux, due it sprite evaluation inaccuracy.

**Comment by retro-wertz** [comment]
i think the core's region-select is hard-coded to retroarch tasks - which doesnt have dendy mode yet.

**Comment by eugene-s-nesdev** [comment]
nestopia-libretro has own region selector in "core options", which include:
"auto", "ntsc", "pal", "famicom", "dendy" modes.

**Comment by retro-wertz** [comment]
nestopia has its region selection code from within the core. fceumm is using retroarch's task. a rewrite or internal region select in the core is probably required.

**Comment by retro-wertz** [comment]
im in the process of adding dendy, seems to work, not quite sure though how it should actually work(50fps  slower audio speed but sound pitch is same as NTSC unlike on PAL mode which audio pitch is also affected.

**Comment by eugene-s-nesdev** [comment]
Maybe this info will be useful:

"Dendy-mode" is basically NTSC mode, but with a longer pre-vblank time,
and running at 50FPS instead of 60FPS. 
This mode allow to run most of NTSC games (Jap, USA) on 50Hz without glitches, with correct DPCM sound pitch also. No need to "autodetect" it via "auto-region". It must be set by user, and emulator should "remember" it.

1:
Here is CORRECT and enough information about timings:
http://wiki.nesdev.com/w/index.php/Clock_rate

differences between NES NTSC/FC, NES PAL, and Dendy:
http://wiki.breaknes.com/_media/wiki:2652378.png?cache=
http://savepic.su/2652378.htm

NMI info:
http://wiki.nesdev.com/w/index.php/NES_2.0#TV_system
http://forums.nesdev.com/viewtopic.php?p=81513#p81513
http://forums.nesdev.com/viewtopic.php?p=147360#p147360

pAPU tables (Noise, DPCМ) are same as NTSC:
http://forums.nesdev.com/viewtopic.php?p=91333#p91333

FCEUX (since svn3111), Nestopia, Nintendulator, puNES, BizHawk, MyNES
and Retrocopy emulators already has support "dendy-mode".
Nintendulator names it as "Hybrid-mode".

2:
Dendy timings have specific behavior, causing some in-game glitches, so here is info "how-to-test dendy-mode":

First ROM is "Battletoads and Double Dragon (U)"
It must look like:
http://hwm.us.to/famimusic/Forum/hardware_tests/game_glitches/Battletoads%20Double%20Dragon.gif

Second ROM is "Choujin Sentai - Jetman (J)"
http://hwm.us.to/famimusic/Forum/hardware_tests/game_glitches/Choujin%20Sentai%20Jetman.gif

Third ROM is "Journey to Silius (U)" (it's DMC test)
Pitch (4 channels + DMC) must be sound like: http://hwm.us.to/famimusic/Forum/Journey_to_Silius_Title.mp3

lastest nintendulator WIP with dendy (aka hybrid) mode:
http://www.qmtpro.com/~nes/nintendulator/nintendulator_bin_unicode.zip
lastest fceux binary:
http://fceux.com/zip

P.S:
"Dendy-mode" is only euphonic name. A thousands of "NTSC/PAL hybrid" famiclones work on this timings.
They have different labels/names in CIS countries ("Dendy", "Lifa", "Kenga", "Subor", etc),
Eastern Europe (i know "Pegasus" in Poland) and Asian region ("MicroGenius" in Taiwan).

**Comment by retro-wertz** [comment]
ok.. kinda looks promising-of course im just doing a blind port+pal_aspect ratio

![fceumm_dendy](https://cloud.githubusercontent.com/assets/23315382/23588666/c983a8ce-01fb-11e7-8b27-b2aa2448ed5c.jpg)

**Comment by eugene-s-nesdev** [comment]
Thank you. If it not so hard, can you please do selectable aspect ratio (by user) in core options, 
which include "NTSC 8:7 PAR"  /   "PAL 11:8 PAR"  /  "4:3 DAR" 
This modes are present in puNES, nestopia-libretro, and Mesen.

**Comment by vadosnaprimer** [comment]
> selectable aspect ratio (by user) in core options,  which include "NTSC 8:7 PAR" / "PAL 11:8 PAR" / "4:3 DAR"

This shouldn't be put so complicated, the only thing that's needed is forcing everything to be 4:3 aspect ratio. Pixel aspect ratio would automatically become 8:7 and 11:8 then. Just show all 240 scanlines in Dendy mode, like PAL does.

**Comment by eugene-s-nesdev** [comment]
Uh, sorry, i see libretro-fceumm already have 4:3 in core options

**Comment by retro-wertz** [comment]
i know some PAL games are just actually NTSC games running 50hz(including the audio) so being able to override PAL games to NTSC is valid, but is there reason to be able to switch PAL games to Dendy?

**Comment by eugene-s-nesdev** [comment]
No reason. Dendy-mode, as Famiclone, was designed to run NTSC games (USA, Japan) on 50 FPS, and keep NTSC-closed timing. So no need to run PAL games on Dendy mode.

Also, some (BUT NOT ALL) models of famiclones, based on classic NTSC-timings (6527/6528 chip series), and Hybrid/Dendy timings (6527P/6538 chip series) have APU duty cycles "bug".
FCEUX also already emulated it - see at "Swap Duty  Cycles" in audio options.
Would be good to set this checkbox to libretro-fceumm core options too.
But this WOULDN'T be enabled by default, only optional.

**Comment by retro-wertz** [comment]
thanks for the info. looks like a quick mod to do,i just dont have know a libretro-related implementation to  reset the core options like this swapduty to appear disabled as default each core launch.

**Comment by eugene-s-nesdev** [comment]
I've compiled and tested your pull-request, it really work awesome.
https://github.com/libretro/libretro-fceumm/pull/83

One note:
Region OSD message appears every time you load ROM, even if region wasn't changed since last ROM you ran.

**Comment by retro-wertz** [comment]
osd is somewhat WIP,  OSD is intentionally done to display if you have forced override region and/or displays current rom region(auto), 

what platform/system you tested this on?

**Comment by eugene-s-nesdev** [comment]
xubuntu 14.04.4 lts x86, on Retroarch 1.4.1

**Comment by retro-wertz** [comment]
tnx for feedback.

**Comment by retro-wertz** [comment]
can we confirm that is is properly working now so we can close thread?

**Comment by eugene-s-nesdev** [comment]
Yes, you can close thread.

**Comment by retro-wertz** [comment]
hehe you can actually close it yourself since your the topic creator :D
