### ISSUE TITLE
Real lightgun sensor input from main FCEU, Feature Request

### ISSUE THREAD

**Issue by riggles1** [libretro/libretro-fceumm#511]
FCEUX has an input dedicated for a lightguns sensor, for use with a real lightgun and modified roms (with adjustable flash delay timings).
http://neslcdmod.com/schemes/

We're a number of people who would like to use our zappers using RA, as RA has support for CRT output, but this would also open up the doors for people wanting to do this with LCD's using raspberry pi NES emulation. 

(for LCD use you need to replace the photo diode to make it work)

**Comment by turley** [comment]
If you haven't already seen it, you might check out this mod: https://github.com/DigiDwrf/libretro-fceumm-zapper-mod

I've merged it into the latest revision (https://github.com/turley/libretro-fceumm), and can confirm it works with a real light gun (and modified rom). For the Digispark version, it just needs retroarch configured with `input_player2_gun_aux_c_btn = "0"` and `input_player2_gun_trigger_btn = "1"`, along with the USB device configured as an `NES Zapper`.

Would love to see something like this merged into libretro-fceumm, but I'm not familiar enough with C or this project to know if the mod breaks anything else, or if it aligns with the project's goals. I imagine @DigiDwrf would be the person to submit a PR.

**Comment by DigiDwrf** [comment]
I've made a PR already, this feature has been merged 😉

@turley thanks again, you rock! check how it worked, I actually merged all functionality under the same device, and added the new light gun mode inside the input options.

This issue can be closed.

**Comment by turley** [comment]
Thanks @DigiDwrf! Looks like a really good solution. 👍

**Comment by turley** [comment]
@DigiDwrf Just FYI - I tried the latest from this repo today, and it doesn't work with my light gun. Not sure if/when I'll have time to debug (the variable names in `zapper.c` are not obvious to me). The trigger is never recognized as a shot in the game.

**Comment by DigiDwrf** [comment]
> ~@DigiDwrf Just FYI - I tried the latest from this repo today, and it doesn't work with my light gun. Not sure if/when I'll have time to debug (the variable names in `zapper.c` are not obvious to me). The trigger is never recognized as a shot in the game.~
> 
> EDIT: Never mind - I had a leftover config option from previous testing that was messing it up. It's working now.

Cool, good to know! No need to worry about the code now or change anyhting. It preserves the same zapper device class it had, I got rid of some unnecessary code, I added a new mode for the device that already was there, and it works as it should. VS. roms are also supported, that's something I put there too, so now it has 100% compatibility with all zapper roms.

I updated the core inside retroarch and now the new mode and options are there, it's official! I'm so happy now :D

**Comment by hizzlekizzle** [comment]
Alright, I guess this issue's clear to close as completed, then?

**Comment by DigiDwrf** [comment]
> Alright, I guess this issue's clear to close as completed, then?

sure, this issue can be closed already! the PR was already merged. 👍
