### ISSUE TITLE
Add More Overscan Cropping Options [Request]

### ISSUE THREAD

**Issue by Awakened0** [libretro/libretro-fceumm#532]
Currently you can only enable symmetrical 8 pixel horizontal and vertical cropping in this core. Mesen allows you to adjust top, bottom, left and right cropping in 4, 8, 12 and 16 pixel increments. Examples of where this can be useful for removing black bars:

Castlevania: 16px top, 16px bottom

![Castlevania (USA)-221021-231058](https://user-images.githubusercontent.com/4565863/197316577-0290f167-0b51-4239-8b51-889e2d651ac7.png)

Castlevania 3: 12px top, 16px bottom

![Akumajou Densetsu (Japan)-221021-231034](https://user-images.githubusercontent.com/4565863/197316586-9edc2787-e1d2-47e0-a88e-d8b31a371052.png)

Ninja Gaiden: 16px top, 8px bottom

![Ninja Gaiden (USA)-221021-231117](https://user-images.githubusercontent.com/4565863/197316594-fe7c911c-a732-4ae2-b878-d4194961c2a1.png)

Ninja Gaiden II: 16px top

![Ninja Gaiden II - The Dark Sword of Chaos (USA)-221021-231144](https://user-images.githubusercontent.com/4565863/197316598-bf4d7c38-43db-464c-89a0-8ca16c6a89c1.png)

Ninja Gaiden III: 16px top

![Ninja Gaiden III - The Ancient Ship of Doom (USA)-221021-231159](https://user-images.githubusercontent.com/4565863/197316602-e49e6b7b-1fec-4326-bb61-0fd7e6f54447.png)

Super Mario Bros. 3: 16px bottom, 8px left, 8px right

![Super Mario Bros  3 (USA) (Rev 1)-221021-231220](https://user-images.githubusercontent.com/4565863/197316605-494e8887-2ba2-409b-a102-b3cee6588219.png)

**Comment by Awakened0** [comment]
I tried it out with Castlevania 1 and Mario 3. Each side's cropping setting works as expected!

**Comment by crashGG** [comment]
> 

could add the same function for [libretro/nestopia](https://github.com/libretro/nestopia) ?
