### ISSUE TITLE
Majority of mapper 256 now getting rejected.

### ISSUE THREAD

**Issue by negativeExponent** [libretro/libretro-fceumm#545]
Mapper 256, although has limited and incomplete to emulated all known variants, should be able to run some of the earlier roms, specifically those that are converted from the xxx-OneBus to NES format. Due to the strict implementation of NES 2.0's console-type header info, most of these rom now rejected and wont run (most of them are VT02)

**Comment by LibretroAdmin** [comment]
> Mapper 256, although has limited and incomplete to emulated all known variants, should be able to run some of the earlier roms, specifically those that are converted from the xxx-OneBus to NES format. Due to the strict implementation of NES 2.0's console-type header info, most of these rom now rejected and wont run (most of them are VT02)

So I got this in my email notification.

Why did you remove the issue?

**Comment by negativeExponent** [comment]
as stated wrong post. or repo. issue not for fceu mm
