### ISSUE TITLE
Add Mapper 413 support (Super Russian Roulette)

### ISSUE THREAD

**Issue by Starman99x** [libretro/libretro-fceumm#556]

**Comment by LibretroAdmin** [comment]
Should be implemented now

**Comment by Tovarichtch** [comment]
Sadly, it's not. Just tried it as of today.

`[libretro WARN]  File contains 8388608 bytes of unused data
[libretro INFO] 
[libretro WARN]  iNES mapper #413 is not supported at all.
[libretro WARN] FDS BIOS ROM image missing!
[libretro WARN] An error occurred while loading the file.`
