### ISSUE TITLE
Add SNES mouse support

### ISSUE THREAD

**Issue by nl255** [libretro/libretro-fceumm#566]
There have been quite a few NES romhacks coming out including one for Maniac Mansion that add support for the SNES mouse to NES games and it would be nice to be able to have those work.  Mesen already supports emulating the SNES mouse for NES games.

**Comment by negativeExponent** [comment]
https://github.com/negativeExponent/libretro-fceumm/commit/c49549af5bd3d493f259ebac6ad5bcf0191e383d
