### ISSUE TITLE
Super Gun (USA) (Unl)

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/libretro-fceumm#567]
Super Gun (USA) (Unl) will only work in Mesen

MD5: 16D8999C8B35C509FC6DD3568C0CEF93

**Comment by LodanZark** [comment]
This core does not support mapper 81

**Comment by negativeExponent** [comment]
https://github.com/negativeExponent/libretro-fceumm/commit/fb10593c6ca345f09e39812d1638d61467676e8c

**Comment by DusanFamicom** [comment]
> This core does not support mapper 81

Yes, NegativeExponent didn't add their update to the public SRC, it's a shame.

**Comment by Cibomatto2002** [comment]
Maybe one day it will be added when someone updates the mappers.

**Comment by Cibomatto2002** [comment]
Maybe it will be Added soon.

https://gitlab.com/jgemu/nestopia/-/commit/5ac45d90d8e1c1ca7a8545df45c17bf9288ba2c9

**Comment by Cibomatto2002** [comment]
I tried this game today and it still does not work.
