### ISSUE TITLE
Message for Negativeexponent

### ISSUE THREAD

**Issue by Cuculcos000** [libretro/libretro-fceumm#578]
Hi, why did you stop posting your posts? It is a great pity that you continue outside.
Can you still consider it?
Thank you for your hard work

**Comment by DusanFamicom** [comment]
I tried it myself, I just didn't know how to put the requests in one download and I still need to write the mappers in Inec.c and Ines.H. Admin please

**Comment by Cuculcos000** [comment]
I tried it myself, I just didn't know how to put the requests in one download and I still need to write the mappers in Inec.c and Ines.H. Admin please

**Comment by negativeExponent** [comment]
they already stole my work even after my work is done! still alot of rewrites to be done. So nothing to cry about now since my work is there. Hope someone will continue to work in it now, including fixing bugs still in the current rebase.

**Comment by LibretroAdmin** [comment]
All the backported changes got reverted, the person pressuring us into adopting these changes sent us on a wild goose chase and later found out all sorts of mappers that were broken. So we reverted it all. We've also told him that we will no longer be  be pressured into adopting code from someone else's fork without measured and verifiable testing being done first.
