### ISSUE TITLE
[feature request] Ability to Disable Turbo

### ISSUE THREAD

**Issue by isugimpy** [libretro/libretro-fceumm#62]
I realize this is kind of an obscure use case, so the priority is relatively low.  This request is to allow a menu mechanism for Turbo functionality to be disabled for the core entirely.  Currently, there's no way to do this that I can find.  You can increase the delay to an absurd number, but the turbo function still works at that point.  What I'm suggesting is either a menu toggle that simply wraps the turbo functionality in the core with an if, or the ability to bind Turbo A and Turbo B to "None", so there is no button which activates them.  Otherwise, the only solution is to use a controller which has few enough physical buttons that they can't be mapped and are thus not pressable.

I realize that in theory, this could be solved by unmapping the buttons in the global config across all cores, but that provides a new problem in that it'd have to be remapped for play on cores which emulate systems which did have those buttons natively.

If the menu toggle is an acceptable design change, I should be able to contribute that back, but I can't seem to find any code quality or design guidelines, so I don't know if that meets the normal design standards.

**Comment by dankcushions** [comment]
> I realize that in theory, this could be solved by unmapping the buttons in the global config across all cores, but that provides a new problem in that it'd have to be remapped for play on cores which emulate systems which did have those buttons natively.

you could unmap via a core override, no?

**Comment by isugimpy** [comment]
Is that an option?  I hadn't found that in the UI, nor a good way to do it via config files.  It's very possible that I overlooked it.  From what I've been able to find, there's only two places to set bindings:  the global, and then in the core itself via the quick menu, which only gives you a pre-defined list of things to map to via left/right scroll.  If that functionality exists, is there any chance you could point me at references to it, documentation if possible?  Otherwise, I'll take another look tonight when I get home from work and try to find it myself, but I spent the last couple days trying to figure this out and haven't yet.

**Comment by dankcushions** [comment]
I haven't tested your specific example, but I think it goes something like this:

1. Load up the core in Retroarch
2. Rebind these buttons to nothing via the global input settings.
3. Go to quick menu > "Save Core Overrides" (it may be in a sub menu within quick menu)

that should save an override in CFG in `/retroarch/configs/FCEUmm/` or similar

**Comment by fr500** [comment]
This is exactly th reason why this should be handled at front-end level and
not in the core

**Comment by isugimpy** [comment]
If this can be done in core overrides, then there's no reason this issue needs to remain open.  I was still running 1.3.6 when I was researching this, and upgraded to latest late last night and didn't catch that feature having been added.  I'll close this and dig further.

**Comment by retro-wertz** [comment]
i was wondering why would someone need to disable turbo buttons when there are enough buttons to use in almost available gamepads when using nes emulator?

i should probably suggest make TURBO_DELAY variable. a game like Double Dragon needs this to be 2(im thinking the turbo are on a per/frame as nestopia is) to be fast enough(sometimes it will not even work with higher than 2) while Double Dragon II needs it to be 3 for the timimg of kick attack,

**Comment by isugimpy** [comment]
It's actually nothing to do with there not being enough buttons.  It's not
wanting the function available.  Not being able to unbind it makes it
impossible for me to remove that function for my son, who has trouble
listening to helpful suggestions and is getting increasingly frustrated
with his inability to maneuver around attacks in Legend of Zelda because
he'll hold the rapid fire A button and be unable to move while his sword
swings wildly.

**Comment by fr500** [comment]
> i was wondering why would someone need to disable turbo buttons when there are enough buttons to use in almost available gamepads when using nes emulator?
> 
> i should probably suggest make TURBO_DELAY variable. a game like Double Dragon needs this to be 2(im thinking the turbo are on a per/frame as nestopia is) to be fast enough(sometimes it will not even work with higher than 2) while Double Dragon II needs it to be 3 for the timimg of kick attack,

Because now I need to remap 4 buttons instead of just moving B and A?
I understand the need for this but we should rather focus on making turbo good in the frontend....

**Comment by isugimpy** [comment]
But isn't this core specific?  The binding of Turbo A and Turbo B is in the core itself, not Retroarch, from what I can tell.  Retroarch (or maybe libretro itself) is binding the buttons on the controller to Retropad virtual buttons, and the core is then mapping those virtual buttons to functions.  In my mind, that's where the change at the core level comes in, to allow full-on unmapping of a button function, rather than just shifting it to a different virtual button, which is what the UI allows right now.  I also discovered last night that the core doesn't respect mapping of a function to "nul", and instead just defaults that function to map to Retropad button B, which I believe is ID 0.

**Comment by hizzlekizzle** [comment]
fr500 is suggesting we just need to beef up the input handling in the frontend to deal with all of this kind of thing, including redundant mapping, more flexible turbo, many-to-one/one-to-many mapping, etc.

While I agree wholeheartedly, it's such a big task that I don't know how realistic it is to plan around it getting done in any foreseeable timeline.

Anyway, I added a core option that lets you enable the turbo buttons for none / p1 / p2 / both, and I'll make the speed variable a core option this evening, probably.
