### ISSUE TITLE
Magic Kid GooGoo mapper is broken

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/libretro-fceumm#63]

**Comment by hizzlekizzle** [comment]
I don't think it's broken, exactly, just doesn't exist, as it's a newly christened mapper that's only used by this game(?):
https://www.dropbox.com/s/xg7qw3unrhb7vs7/magic%20kid%20googoo%20mapper.txt?dl=0

**Comment by Monroe88** [comment]
FCEUX implemented the new mapper as well.

https://sourceforge.net/p/fceultra/code/3334/

**Comment by hizzlekizzle** [comment]
Fixed by:
https://github.com/libretro/libretro-fceumm/commit/13f6f51641c878bca79dd07662d04b05fe1f1a82
