### ISSUE TITLE
[feature request]Support for soft-patching 

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-fceumm#68]
Currently, fceumm does not do soft-patching(or if it was intended to do so internally, then its not working for some reasons). i tested the patch files in other emu and make sure they are indeed working.

a discussion in irc leads that **info->need_fullpath = true;** should be set to "false" for retroarch's internal softpatching to do this. setting this value to "false" does make soft patching work as seen in screenshot:

**Getsu Fuuma Den (Japan).nes**
![fceumm](https://cloud.githubusercontent.com/assets/23315382/23097772/25c3f0f6-f678-11e6-8ee2-a7fa3e8f0141.jpg)
-other games like Wai Wai World is also tested to work fine. also using bps and ups patch works.

BUT, it is also said that the core has to recognize this change in value do the proper implementation to make this "safe" to use. i do not know the technical stuffs behind it but i do hope this will be a feature that will be implemented in the core for a few reason : 
1-its a retroachievement compatible core(more or less), 
2-loads soft patch without crashing(atm) -

Thanks.

ISSUES FOUND:
-fds softpatching fails to load fds games(turns out to be rom header issue and not related to this)
-extracted roms are not deleted when closing core...UPDATE - this might possible be solved(hope so)...**solved!**
-probably other cleanup required and/or memory leak issues.

**Comment by hizzlekizzle** [comment]
In addition to just changing "needs_fullpath" to false, all of the instances of fopen() have to be removed, and there are quite a few sprinkled about.

**Comment by retro-wertz** [comment]
-a bug is found! cannot load FDS roms correctly when using soft-patch with above modification. FDS will either give disk error messages in bios screen or will just go into reboot loop.
-turns out this is not a fcuemm mod issue since this happens to other emulators also when using soft-patches.
-upon investigation, turns out that most translations/hacks are expecting the 16 bytes rom header for FDS, while No-Intro dat has rom header ignore, resulting to most downloadable FDS dumps do not have this header.
-adding the correct 16 bytes header to the rom should make most patches work.
-alternatively, you can remake the patch by patching the rom with correct header, apply hard-patch to the rom, then remove the header  and recreate a new patch file (ips, ups, bps)

**Comment by retro-wertz** [comment]
**found an issue, extracted roms are not deleted when closing core...**

**Comment by retro-wertz** [comment]
UPDATE : regarding extracted roms not deleted
-after sometime looking blindlessly at code ( im no dev or programmer, im more on tracing and trial and error) i may have found a solution. it does delete the extracted rom now after closing core - im just not quite sure yet if there are any other issues like memory leaks or such. i did play and finish a few games without much issue so there probably is no gameplay related issue.
-really need help regarding this. i believe softpatching is a decent feature to add.

**Comment by retro-wertz** [comment]
currently im in the middle of making new proposal. we can safely skip the file IO "fopen" calls from FCEU_fopen() since normal roms and FDS will already have buffers (directly from game->data). 
*something like moving "void *t = fopen(path, mode);" to 
if (buffer)
else
   t = fopen(path, mode);
endif
https://github.com/libretro/libretro-fceumm/blob/master/src/file.c#L84

but fopen cannot be totally removed from this function (at least from what i gathered around). the remaining fopen from this FCEU_fopen()  is used directly in path when using FDS. its used when loading the bios file, reading from the saved file and saving the savefile after closing core which should just immediately be terminated with fclose right after doing this and load in memory
**bios read**  = https://github.com/libretro/libretro-fceumm/blob/master/src/fds.c#L616
**load savefile** - https://github.com/libretro/libretro-fceumm/blob/master/src/fds.c#L671
**write savefile** (upon calling close core) - https://github.com/libretro/libretro-fceumm/blob/master/src/fds.c#L739

other fopen,fclose,fread calls are used by debugger,cheats,fceu routing savegame,loadgame, palettes, savestates which are not used(each passed to FCEU_MakeFName which they dont have the routine implemented anyways) by retroarch/libretro since we have our own way for this things. 

if anyone can shed more information for this implementation and/or how this should be implemented (reference to the proposal PR from above) it would be of help. i think adding softpatch is a good feature,  considering it should be working already.

@hunterk @meepingsnesroms @Tatsuya79

**Comment by bparker06** [comment]
I didn't think _all_ the fopen should disappear, just ones related to reading the game rom.

**Comment by retro-wertz** [comment]
i am thinking of something like this to FCEU_fopen()

https://hastebin.com/olahapuxil.cpp

only 3 things passes to this: normal ines roms, fds roms and savefile loading from fds, (also nsf if we want to since it just needs edit on fceumm_libretro.info to enable nsf read. core already can play nsf aside from the graphical issue during playback)

**Comment by retro-wertz** [comment]
UPDATE: since fullpath=false is now official. should the proposal above implemented too so that the extracted rom will be deleted upon closing rom and "game->path" wont necessarily pass to an fopen call? 

*void *t = fopen(path, mode)* (NOTE: opening the FDS savefile still passes tru here because that has no buffer) https://github.com/libretro/libretro-fceumm/blob/master/src/fds.c#L671

**Comment by retro-wertz** [comment]
this should be OK now. just re-open if related issues arises....
