### ISSUE TITLE
[Android][Segfault] when overclocking is enabled/disabled

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-fceumm#73]
When enabling the overclock option, returning to the game crashes retroarch. Previous commits from Dec 2016 does not crash.

backtrace - https://hastebin.com/zagedokequ.cs

1st broken commit https://github.com/libretro/libretro-fceumm/commit/7fb6b0485a7935eb85354b76d165b1804c22c4cc

a revert seems to have been done but its not fully reverted. is the crashing an accidental effect of the new code layout? im no coder/developer so i do not know which one of the previous commit should be the right one.

thanks
#58

**Comment by retro-wertz** [comment]
@twinaphex can you take a quick look at this when your free? :-)

**Comment by twinaphex** [comment]
You might want to invite @aliaspider into this discussion. We have previously been struggling with that portion of the code.

**Comment by retro-wertz** [comment]
@aliaspider

**Comment by retro-wertz** [comment]
@twinaphex @aliaspider i was messing around with the core trying to add dendy support. whenever dendy mode was enabled(making normal_scanlines = 290 compared to default 240), it would crash closing it. tracing it lead me to have been caused when free(XBuf) is called.

this lead me to this code from fceux commit r3231:
-uint8 *target = XBuf + (scanline << 8);
+uint8 *target = XBuf + ((scanline < 240 ? scanline : 240) << 8);

this solved my XBuf issue with dendy mode and it also remove crash when overclock is enabled.

**Comment by blackman91** [comment]
Still crashing for me, has this been already merged?

**Comment by blackman91** [comment]
Yep still crashing on android when enabling overclock in the core options, using the latest nightly and core.

**Comment by retro-wertz** [comment]
@blackman91 - android is not currently building. wait awhile till it gets fixed.

**Comment by retro-wertz** [comment]
@blackman91 - this should be fixed now in this commit https://github.com/libretro/libretro-fceumm/commit/315a1e59242f3202e39d82f900137748d248b468

i've tested already in my android. please confirm on your end.
