### ISSUE TITLE
Overclocking causes short audio in blaster master

### ISSUE THREAD

**Issue by phly95** [libretro/libretro-fceumm#79]
Blaster Master is definitely a game that needs overclocking in order to run properly (it can run really slow at times). Unfortunately, it seems that while it does run well mostly with the overclock, and is much smoother, unfortunately, many (mostly the background notes and cymbals rather than the main melody) of the notes and sfx seem to be playing for half the time they are supposed to. Is there a way the game can be hacked to work with overclocking without audio issues for most of the game?

**Comment by meepingsnesroms** [comment]
This also happens on smb1 death, it may not be fixable since the audio is going as fast as it can and the CPU is going faster than it should.

**Comment by phly95** [comment]
could it be possible to essentially convert a single frame sound to a double frame sound? maybe extract the audio, modify it, and inject it back into the game with it fixed? I'm not familiar with how the NES works, so this could be totally wrong

**Comment by phly95** [comment]
OK, I was looking through emulators, and while many have this issue, mesen actually does not. So it is a possible fix. Not sure how mesen acheives this, but I was able to set the overclock up to 1000% with no audio issues at all. Maybe we need a mesen core for libretro

**Comment by meepingsnesroms** [comment]
I will try to implement there fix, the texture packs seem worthless since I could not even find 1.

The overclock is done by doubling the screen size, so it is hacky and that is likely the problem.

**Comment by phly95** [comment]
I bet the reason for texture packs being almost non-existent is because most emulators don't support it, rather than the other way around, though I can see how it would be hard to implement and isn't really that important of a feature. I'm surprised any nes emulator has that feature at all. Imagine all the color mods that would be possible. NES games could all get 16 bit upgrades to look like modern retro style games.

**Comment by meepingsnesroms** [comment]
I changed how pcm sample detection works with overclock, could you test again?(And tell me if it caused any new issues)

**Comment by phly95** [comment]
how do I get the buildbot version? I tried using the online updater in retroarch and it seems to be the same

**Comment by meepingsnesroms** [comment]
What platform are you on?
Many buildbot platforms are broken.
Linux and android build bot are working.

**Comment by phly95** [comment]
I'm on Windows

**Comment by retro-wertz** [comment]
fix merged. hope buildbot updates fast.

**Comment by retro-wertz** [comment]
@phly95 can we get confirmation now if this issue is resolve so we can close related issues?

**Comment by phly95** [comment]
Sorry about the wait, yeah, the issue seems to be fixed now. Thank you.
