### ISSUE TITLE
!square audio channel issues when overclocked

### ISSUE THREAD

**Issue by retro-wertz** [libretro/libretro-fceumm#81]
*square channel 1 - pitch issue
*square channel 2 - short burst

pitch issue when overclocked is enabled. bisected it to be on square channel 1.
most noticeable when jumping in Double Dragon II.

related to the newly posted issue regarding short audio bursts: (square channel 1) (test in Contra Intro sound, jumping golem thing in stage 1 of Blaster Master)
#79 
Sorry. it seems that the jumping sfx for that Golem is square channel 2, so both audio channels affected on overclock depending on how the affected games access square channels?

on a related note - bufferoverruns
#73

**Comment by meepingsnesroms** [comment]
Did this happen before my change too?

**Comment by retro-wertz** [comment]
yes, thats an existing issue i just have noticed that new posted issue when i was writing this one so i just did quick test and tagged.

**Comment by meepingsnesroms** [comment]
Is this resolved?

**Comment by retro-wertz** [comment]
fixed https://github.com/libretro/libretro-fceumm/commit/6c71d261cceac9d5a4be62ecd0721a572a14d338
