### ISSUE TITLE
sound quality (core option)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [libretro/libretro-fceumm#85]
FCEU/FCEUmm/FCEUX-core has 3 values of sound quality:
```
-low
-high
-highest
```
Current libretro-fceumm use "low" as default, as well, as FCEU and FCEUmm by Cah4e3.
New FCEUX 2.2.3 uses "high" as default.
Main problem are that FDS PCM-channel (and other external PCM-channels) of FCEU core
sounds very poor on low-quality, especially if NES CPU speed is lower than default NTSC ~1.79 MHz. 
For example "Arumana no Kiseki" game soundtrack sounds bad on PAL (~1.66 Mhz CPU speed) and Dendy (~1.77 Mhz CPU speed).
If user set "high" or "highest" quality - all this problems are completely gone!
(the "highest" sound quality mode is similar to the normal high-quality mode, but the filters are of a higher order 1024 coefficients). 
http://panic.klippanlan.net/Nintendo/fceultra.html#features-sound
Yes, it's CPU intensive, but if user have modern ARM (Rpi2 and higher) or x86 intel Atom z8xxx series, there are no problem with it.

Good variant is add sound quality selector in core options, default=low (for users who have old low-powered CPU)

**Comment by retro-wertz** [comment]
currently, the core is set at quality=0, soundrate = 32050.50Hz, probably at that time to support slower devices. i tried modding this stuff to selectable sound quality and rate, but a am not hearing much difference from the core(subtle difference with standalone-probably of how RA interfaces with the audio? mixing its own stuff in?) but sad to say i am not able to test 96000Hz mode, RA does not run with it, it seems.

if you can the time, you can test-compile this https://github.com/retro-wertz/libretro-fceumm/tree/audio_test

it has variable audio quality and rate. though when setting Rate, you need restart core. there is no guarantee that its doing what its suppose to but there is a debug text in debug window to show that the values are passed to sound.c and filter.c

qualility = 1(high), soundrate 441000 should be enough for most stuff, including turning ON sound stuff in fds, vrc6,7 etc.

**Comment by eugene-s-nesdev** [comment]
```
src/boards/unrom512.c:210:4: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [src/boards/unrom512.o] Error 1
```

**Comment by retro-wertz** [comment]
im not familiar fixing compiler issues :D does not seem to be an issue here using msys2 gcc 6.3.0. anyways just delete the file, and edit ines.c, unif.c unif.h and remove those UNROM512_init stuff

anyways this is just a debug build to test the audio.

**Comment by eugene-s-nesdev** [comment]
I deleted all related to unrom512.
Sorry but i still can't compile this build.

```
src/drivers/libretro/griffin.o: In function `FCEUI_SetRenderedLines':
griffin.c:(.text+0x8930): undefined reference to `dendy'
src/drivers/libretro/griffin.o: In function `FCEUI_GetDesiredFPS':
griffin.c:(.text+0x89c4): undefined reference to `dendy'
src/drivers/libretro/griffin.o: In function `MakeFilters':
griffin.c:(.text+0x933b): undefined reference to `dendy'
src/drivers/libretro/griffin.o: In function `FCEUPPU_SetVideoSystem':
griffin.c:(.text+0xfe37): undefined reference to `dendy'
src/drivers/libretro/griffin.o: In function `SetSoundVariables':
griffin.c:(.text+0x11315): undefined reference to `dendy'
src/drivers/libretro/griffin.o:griffin.c:(.text+0x116ec): more undefined references to `dendy' follow
collect2: error: ld returned 1 exit status
make: *** [fceumm_libretro.so] Error 1
```

**Comment by retro-wertz** [comment]
oh i see whats happening, you pulled this and overwritten the PR i did awhile back. this set is different, its a different branch. compile this separately. anyways. your on windows x64 right? i can just compile one.

**Comment by eugene-s-nesdev** [comment]
No, im on xubuntu 14.04.1 LTS, can you send me right sourcepack on evgs1987@mail.ru ?

**Comment by retro-wertz** [comment]
wait try pulling it again, on a new folder if possible. i edited stuff there.

**Comment by eugene-s-nesdev** [comment]
Compiled. 
Strange thing:
on 32040.50 Hz gamespeed and sound tempo is normal
on 44100 Hz framerate is lower, sound tempo and pitch also lower.
on 48000 Hz all this things are lower than on 44100 too.

**Comment by retro-wertz** [comment]
as as i said above. when changing rate, restart core

**Comment by eugene-s-nesdev** [comment]
Okay, i tested this. Seems all works good with no-crashes.
As i said, 4800Hz (in GUI) is typo, this should be 48000Hz

**Comment by retro-wertz** [comment]
just ignore typos for now hehe. just try test it, and if indeed there are differences. if there is no difference where-in it should have, just post findings, i might make proper PR if it does not need lots of stuff for the mods required. again this is a debug-test build only

**Comment by eugene-s-nesdev** [comment]
At least i can hear the difference between 32040.50 / 44100 and low / high 
If you're interested, try to listen "Solstice" game (1st level), or
"Streemerz" (high-pitch sound when FAUX logo appears)

**Comment by retro-wertz** [comment]
ok, sound quality "does" enable separate audio channels. quality 0 mixes channels (some low notes in can be heard in Streemerz intro, while quality 1 make it more high pitch tone.

can probably propose for core option Sound Quality, but Sound Rate doesnt seem to be an option, because this cannot be changed only-the-fly in RA-core has to be restarted with new sampling rate(not entirely sure though-still nid to ask around)

**Comment by eugene-s-nesdev** [comment]
Anyway, "settings->"audio"->"audio_output_rate" are real physical output. 
In most cases this is 44100 or 48000 (native rate for all modern soundcard)
And i think retroarch interpolate fceumm's "32040.50" to most common output rate 44100 or 48000 via 
"driver"->"audio resampler driver".

Maybe better to kick-out 32040.50 and switch to more modern 48000, it's not so CPU intensive

**Comment by meepingsnesroms** [comment]
Why don't we just set this to  the highest value?

Are there any platforms that are that slow they can't accurately emulate a NES.?

**Comment by eugene-s-nesdev** [comment]
Maybe you're right. And 48000 Hz with "highest" quality will be enough by default.

**Comment by dankcushions** [comment]
i believe this core can have bad performance on a pi zero/rpi1. yet nestopia is normally fine (and i hear has better sound emulation anyway).

**Comment by eugene-s-nesdev** [comment]
Nestopia is cycle-accurate emulator, FCEUmm/FCEUX isn't.
But nestopia is highly-optimized, so it's performance are same as fceumm+lowsoundquality.

http://forums.nesdev.com/viewtopic.php?f=3&t=15532
Nestopia is fastest cycle accurate emulator ever made.

**Comment by meepingsnesroms** [comment]
Retropi can compile with it set to "low" if they want, this would just be a #ifdef and all other platforms will use highest.

If the device can support high quality audio at fullspeed why would you turn it off?

**Comment by hizzlekizzle** [comment]
There's also Lakka and 3DS and PSP etc., all of which rely on FCEUmm for NES. We should do some testing to see if the higher quality sound makes a significant impact on CPU load, particularly with these platforms in mind.

If you can make it a core option, even if it require a reinit of the core, the safest thing would be to default to fast/poor quality and then higher-powered platforms can crank up the quality.

**Comment by retro-wertz** [comment]
i have an experimental fork with sound quality and sound sample rate set to variable settings. Sound quality change does not need core re-init, but sample rate changes does(probably because of retro_system_timing.sample_rate). i cant seem to find somebody with those devices though to do test.

One small cons of setting sound quality at >= 1 though is audio pop when changing between quality, sound rates or region changes-this does happen to all fceu-based cores though

**Comment by retro-wertz** [comment]
here is the test branch with quality and sample rate adjustable. USE SEPARATE FOLDER FOR THIS!
https://github.com/libretro/libretro-fceumm/compare/master...retro-wertz:audio_test
NOTE: changing sound rate requires restart of core or timing mismatch will occur.

**Comment by hizzlekizzle** [comment]
@dankcushions 
Would you be able to test that branch for us and see if it affects performance substantially on an RPi (model 1, if you have one; the weaker the better)?

**Comment by dankcushions** [comment]
@hizzlekizzle i'm afraid i don't have one. i was basing my comments on what users have said on the retropie forums. e.g. https://retropie.org.uk/forum/topic/7923/switching-default-nes-emulator-opinions-wanted

@joolswills might be able to help though.

however incidentally i noticed that rpi3 + the regular build of fceumm + crt-pi shader would drop frames. if i used the same shader with nestopia core, it's fine. the rpi's have shared memory and such, so it's possible that fceumm hammers the system bandwidth enough that shader performance suffers. emulation on pi systems is always a delight :)

**Comment by eugene-s-nesdev** [comment]
So, if "very high" is much more CPU-intensive than "low", there are only one possible way to satisfy
all users:
```
- set default rate to 44100 or 48000 instead of 32040.50 kHz  
- make quality selector in core options, as @retro-wertz did in "audio_test" branch
```

**Comment by retro-wertz** [comment]
im kinda confuse why Nestopia would perform better when it has a RETRO_ENVIRONMENT_SET_PERFORMANCE_LEVEL at 6 while fceumm is at 5? Of course it could be how both differ in emulating gfx but is there anything else?

**Comment by Monroe88** [comment]
You can call RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO to change timing.sample_rate or timing.fps, it will force a reinit of the frontend.

https://github.com/libretro/libretro-samples/blob/master/tests/test/libretro-test.c#L344

**Comment by retro-wertz** [comment]
anyone is able to compile psp, rpi, or any of the supported slower devices so we can update core to have 44100Hz-High Quality mode?

**Comment by eugene-s-nesdev** [comment]
I have RPI3 with lastest Lakka. If anyone will compile fceumm libretro core with sound patches, i'll can test it.
I also have ASUS eeepc based on intel Atom N550 @1.50 GHz, it works good with 44100/HQ mode,
tested on lubuntu 14.04 x86

**Comment by eugene-s-nesdev** [comment]
Here is test of different nes cores with no throttling (space) on the Atom N550
So you can see maximum FPS on available on this CPU
[libretro_nothrottle_atomN550_lubuntu_x64.zip](https://github.com/libretro/libretro-fceumm/files/1016289/libretro_nothrottle_atomN550_lubuntu_x64.zip)

**Comment by retro-wertz** [comment]
are you able to modify and compile from source? change soundrate to 441000 and enable soundquality(1) and compare?

**Comment by hizzlekizzle** [comment]
Am I correct in thinking that halves the framerate? If so, yikes, that's a pretty big hit.

**Comment by eugene-s-nesdev** [comment]
Yes. "Low" and "High" quality must be optional.
48000Hz is enough for both. RPI with lastest lakka has 48000Hz by default, 
and most of soundcards have native multiple 48000 / 96000 (48x2) /192000 (48x4) Hz generator, so some aliasing presents on 44100Hz

**Comment by retro-wertz** [comment]
Sound Quality - Revisited:

Did some quick tests Using "top" on terminal:
on Low, cpu usage is averages about 6% peaks at 10%, 
High = 12%, peaks 16%
Very High = 16%, peaks at 20%

Nestopia is behaving like its using High for soundquality.
Quickness uses lower than Low setting, peaks at 6% only

These are taken with sample rate at 48,000.0 on dual-core cpu. Using 32k-48kHz doesn't seem to affect cpu usage for given sound quality, nor does using roms with special sound chips on them(tested on FDS Armani ni Kiseki and cart roms like Akumajo Dracula). Of course this would mean different to slower devices. Dont have such devices nor a way to compile it though.

Over at retropie  and i think they prefer more using fceumm due to performance and features especially overclocking and retroachievements. Who cares how Super Mario's "death" sound like.

Only downside is the audio "pop" when changing some timing-related option like region select.

Either the core option should be enabled but set to default Low for all system, or the core option is only enabled to some systems(like general unix and windows?)

I still have no idea to what sample frequency to use as to minimize possible artifacts due to resampling and such.

**Comment by eugene-s-nesdev** [comment]
The core option should be enabled for all systems, but set to Low as default.
I guess default samplerate should be 48000, nestopia use it too:
https://github.com/rdanbrook/nestopia/commit/3f9b42c3ce00dce134255c5868572951d637bcc0

**Comment by retro-wertz** [comment]
mednafen-nes, which also uses fceu base is set to 48000 Hz default.

**Comment by hizzlekizzle** [comment]
option enabled, low by default, 48khz default sample rate seems like a good plan to me.

**Comment by retro-wertz** [comment]
-Sound Quality should now be configurable in core options. 
-48kHz is also set as default sample rate. 
-Also included is volume adjustment(default was 100)
-as bonus, 4player fourscore or famicom 4p should be playable now(by crc for now), and also ZAPPER support for normal carts and VS Unisystem roms.

**Comment by eugene-s-nesdev** [comment]
Thank you, retro-wertz!
Maybe i'll do performance test on Samsung Galaxy S2 and RPI3 soon

**Comment by retro-wertz** [comment]
any update? whats your findings regarding performance?

**Comment by eugene-s-nesdev** [comment]
Will do when lakka 2.1 will release. I need native and fresh RPI3 fceumm core

**Comment by retro-wertz** [comment]
ok thats good to hear. just update the post.

thanks.

**Comment by eugene-s-nesdev** [comment]
Do you know how to build fceumm and nestopia cores from source for RPI2/RPI3 target?
Or maybe some howto instructions available on internet?
Host machine running on xubuntu 16.04 x86_x64

**Comment by retro-wertz** [comment]
i am not sure as to i dont have rpi, but it should be similar to compiling in linux. just needed the correct libraries to use. if the steps are indeed compatible(since you are using ubuntu based) then it should be not that hard.

maybe @hizzlekizzle  or @dankcushions can help better.

**Comment by eugene-s-nesdev** [comment]
Yes, thank you.
I'm not familiar how to change default compiler and --prefix / --target parameters.
I've installed gcc-arm-linux-gnueabihf package (with all it's dependences)

fceumm Makefile.libretro contains
```
# Raspberry Pi 2
else ifeq ($(platform), rpi2)
	TARGET := $(TARGET_NAME)_libretro.so
	fpic := -fPIC
	SHARED := -shared -Wl,--version-script=src/drivers/libretro/link.T -Wl,-no-undefined
	CFLAGS += -DARM
	CFLAGS += -marm -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -funsafe-math-optimizations
	CFLAGS += -fomit-frame-pointer -fstrict-aliasing -ffast-math
```
So i will try to ask somebody for help

**Comment by retro-wertz** [comment]
its normally just typing "make" from the fceumm folder, incase all libs are already there. i dont think there is a need to specifically indicate "platform" unless you are cross-compiling.

**Comment by eugene-s-nesdev** [comment]
Hi, fix core option GUI typo please:
https://github.com/libretro/libretro-fceumm/commit/2cdf32300b86d291345924938d1b782a5634ec8f

cycles, not cyles

**Comment by retro-wertz** [comment]
thanks for the correction....

**Comment by eugene-s-nesdev** [comment]
Here is Raspberry Pi 3 test, on Lakka with recent fceumm_libretro core (ARMHF)
Very good results, it can run 60FPS fullspeed even on very high quality:

https://youtu.be/ob9j4bF6N2c

**Comment by retro-wertz** [comment]
thanks for test. this should be safe to close now then....
