### ISSUE TITLE
Both "Postrender" and "Vblank" overclock methods

### ISSUE THREAD

**Issue by eugene-s-nesdev** [libretro/libretro-fceumm#91]
Current libretro-fceumm has "Postrender" overclock method only.
But users need both "Postrender" and "Vblank" methods.
Why?
Some games, like Contra Force are unplayable (level 3) on Postrender overclock
Some other games (Battletoads/BT&D.D.), vice versa, are unplayable on Vblank overclock. 

Current libretro-fceumm has:
```
-disabled
-2x overclock (in real it's Postrender method, seems has 266 scanlines)
```
Will be good to see:
```
-disabled
-2x PR
-2x VBL
```
SEE THIS VIDEO:
https://youtu.be/EPqekMi19h8

**Comment by retro-wertz** [comment]
vblank atm cannot be implemented, unless able to reset the setting back to
disabled everytime. i did this before and slows down game the next run.
kinda annoying.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by eugene-s-nesdev** [comment]
Okay, thx for answer.
It's really fceumm "2x" overclock = FCEUX Postrender overclock with 266 scanlines exactly?

**Comment by retro-wertz** [comment]
yes, its post render at 266 extralines for that 2x(ish)boost

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by retro-wertz** [comment]
if you want to experiment or test something out, i have uploaded an experimental branch with vblank method enabled.

in order to use each overclocking method, you MUST switch back to "disable" first before selecting the other overclock method. not doing so will either not enable that overclock mode or cause wierdnes.
https://github.com/retro-wertz/libretro-fceumm/tree/add_vblank_oc
*pull and compile to a different folder*

**Comment by eugene-s-nesdev** [comment]
Thank you. I did all the steps you're said, it works correct.
I tested it with Contra Force (level 3).

**Comment by retro-wertz** [comment]
@eugene-s-nesdev - if you have the time compile and test this. this should be based on latest commits and able to choose between vblank and postrender on the fly.

https://github.com/retro-wertz/libretro-fceumm/tree/overclocking

**Comment by eugene-s-nesdev** [comment]
Thank you. I've compiled your overclock branch and tested this on Contra Force.
Seems all works correct.

**Comment by retro-wertz** [comment]
thanks. the code is already pushed into the current version. so if its not causing any issues we may probably be able to close this issue  :D

**Comment by hizzlekizzle** [comment]
Sounds good :)

Feel free to reopen if any problems pop up.
