### ISSUE TITLE
Turbo A and Turbo B stop working after upgrade from ver 1.41 to 1.5

### ISSUE THREAD

**Issue by koukakou** [libretro/libretro-fceumm#92]
Turbo buttons used to work perfectly before upgrade. Now it doesn't work. Key bindings are correct. RetroPie 4.1. 

Replace fceumm_libretro.so with the previous version. Turbos come back.

**Comment by retro-wertz** [comment]
there must be something wrong from your end. i have been using fceumm for
all nes/fds stuff. there is an Turbo OFF on later versions of fceumm, check
that those are not disabled.

**Comment by hizzlekizzle** [comment]
I think the core options changed just a bit, so you may need to go in and re-enable it.

**Comment by koukakou** [comment]
so where is the config option to switch turbo on or off?

**Comment by eugene-s-nesdev** [comment]
I don't used RetroPie, have only Lakka. Try to find "options" menu (core and ROM must be loaded).
It looks like: http://savepic.su/7618934.png

**Comment by meleu** [comment]
Yeah, the turbo can be enabled in the core options. I think this issue should be closed.
